<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Descriptives | PSY317L &amp; PSY120R Textbook</title>
  <meta name="description" content="Chapter 6 Descriptives | PSY317L &amp; PSY120R Textbook" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Descriptives | PSY317L &amp; PSY120R Textbook" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Descriptives | PSY317L &amp; PSY120R Textbook" />
  
  
  

<meta name="author" content="James P. Curley &amp; Tyler M. Milewski" />


<meta name="date" content="2021-09-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-visualization.html"/>
<link rel="next" href="distributions.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to Statistics & R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to PSY317 / PSY120R !</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#what-this-book-includes-and-what-it-doesnt"><i class="fa fa-check"></i><b>1.1</b> What this book includes and what it doesn’t</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#how-to-use-this-guide"><i class="fa fa-check"></i><b>1.2</b> How to use this guide</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>1.3</b> Acknowledgements</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#references"><i class="fa fa-check"></i><b>1.4</b> References</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#other-places-to-find-help-about-r-and-statistics"><i class="fa fa-check"></i><b>1.5</b> Other places to find help about R and Statistics</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#downloading-r"><i class="fa fa-check"></i><b>2.1</b> Downloading R</a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#downloading-rstudio"><i class="fa fa-check"></i><b>2.2</b> Downloading RStudio</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="introduction.html"><a href="introduction.html#successful-installation"><i class="fa fa-check"></i><b>2.2.1</b> Successful installation</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction.html"><a href="introduction.html#using-rcloud"><i class="fa fa-check"></i><b>2.3</b> Using RCloud</a></li>
<li class="chapter" data-level="2.4" data-path="introduction.html"><a href="introduction.html#the-rstudio-environment"><i class="fa fa-check"></i><b>2.4</b> The RStudio Environment</a></li>
<li class="chapter" data-level="2.5" data-path="introduction.html"><a href="introduction.html#running-code"><i class="fa fa-check"></i><b>2.5</b> Running Code</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introduction.html"><a href="introduction.html#the-console"><i class="fa fa-check"></i><b>2.5.1</b> The Console</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction.html"><a href="introduction.html#rscript"><i class="fa fa-check"></i><b>2.5.2</b> RScript</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction.html"><a href="introduction.html#saving-an-rscript"><i class="fa fa-check"></i><b>2.5.3</b> Saving an RScript</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction.html"><a href="introduction.html#open-an-existing-rscript"><i class="fa fa-check"></i><b>2.5.4</b> Open an existing RScript</a></li>
<li class="chapter" data-level="2.5.5" data-path="introduction.html"><a href="introduction.html#running-code-in-scripts"><i class="fa fa-check"></i><b>2.5.5</b> Running Code in Scripts</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="introduction.html"><a href="introduction.html#packages"><i class="fa fa-check"></i><b>2.6</b> Packages</a></li>
<li class="chapter" data-level="2.7" data-path="introduction.html"><a href="introduction.html#working-with-rstudio-in-psy317l"><i class="fa fa-check"></i><b>2.7</b> Working with RStudio in PSY317L</a></li>
<li class="chapter" data-level="2.8" data-path="introduction.html"><a href="introduction.html#quitting-rstudio"><i class="fa fa-check"></i><b>2.8</b> Quitting RStudio</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basic-syntax.html"><a href="basic-syntax.html"><i class="fa fa-check"></i><b>3</b> Basic Syntax</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basic-syntax.html"><a href="basic-syntax.html#simple-mathematical-syntax"><i class="fa fa-check"></i><b>3.1</b> Simple mathematical syntax</a></li>
<li class="chapter" data-level="3.2" data-path="basic-syntax.html"><a href="basic-syntax.html#assignment"><i class="fa fa-check"></i><b>3.2</b> Assignment</a></li>
<li class="chapter" data-level="3.3" data-path="basic-syntax.html"><a href="basic-syntax.html#vectors"><i class="fa fa-check"></i><b>3.3</b> Vectors</a></li>
<li class="chapter" data-level="3.4" data-path="basic-syntax.html"><a href="basic-syntax.html#characters"><i class="fa fa-check"></i><b>3.4</b> Characters</a></li>
<li class="chapter" data-level="3.5" data-path="basic-syntax.html"><a href="basic-syntax.html#naming-of-objects"><i class="fa fa-check"></i><b>3.5</b> Naming of objects</a></li>
<li class="chapter" data-level="3.6" data-path="basic-syntax.html"><a href="basic-syntax.html#logical-operators"><i class="fa fa-check"></i><b>3.6</b> Logical Operators</a></li>
<li class="chapter" data-level="3.7" data-path="basic-syntax.html"><a href="basic-syntax.html#some-things-that-are-useful-to-know."><i class="fa fa-check"></i><b>3.7</b> Some things that are useful to know.</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="basic-syntax.html"><a href="basic-syntax.html#tab-is-your-friend"><i class="fa fa-check"></i><b>3.7.1</b> Tab is your friend</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="basic-syntax.html"><a href="basic-syntax.html#error-messages"><i class="fa fa-check"></i><b>3.8</b> Error Messages</a></li>
<li class="chapter" data-level="3.9" data-path="basic-syntax.html"><a href="basic-syntax.html#functions"><i class="fa fa-check"></i><b>3.9</b> Functions</a></li>
<li class="chapter" data-level="3.10" data-path="basic-syntax.html"><a href="basic-syntax.html#chaining-syntax"><i class="fa fa-check"></i><b>3.10</b> Chaining Syntax</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html"><i class="fa fa-check"></i><b>4</b> Introduction to Data Carpentry</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#data-types"><i class="fa fa-check"></i><b>4.1</b> Data Types</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#categorical-data"><i class="fa fa-check"></i><b>4.1.1</b> Categorical Data</a></li>
<li class="chapter" data-level="4.1.2" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#numerical-data-discrete-vs.-continuous"><i class="fa fa-check"></i><b>4.1.2</b> Numerical Data (Discrete vs. Continuous)</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#importing-data"><i class="fa fa-check"></i><b>4.2</b> Importing Data</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#introduction-to-dataframes"><i class="fa fa-check"></i><b>4.3</b> Introduction to Dataframes</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#dataframe-basics"><i class="fa fa-check"></i><b>4.3.1</b> Dataframe basics</a></li>
<li class="chapter" data-level="4.3.2" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#indexing-dataframes."><i class="fa fa-check"></i><b>4.3.2</b> Indexing dataframes.</a></li>
<li class="chapter" data-level="4.3.3" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#adding-and-removing-columns"><i class="fa fa-check"></i><b>4.3.3</b> Adding and removing columns</a></li>
<li class="chapter" data-level="4.3.4" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#structure-of-datasets"><i class="fa fa-check"></i><b>4.3.4</b> Structure of Datasets</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#manually-creating-a-dataframe"><i class="fa fa-check"></i><b>4.4</b> Manually creating a Dataframe</a></li>
<li class="chapter" data-level="4.5" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#tidyverse"><i class="fa fa-check"></i><b>4.5</b> tidyverse</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#table"><i class="fa fa-check"></i><b>4.5.1</b> table()</a></li>
<li class="chapter" data-level="4.5.2" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#filter---subsetting-data"><i class="fa fa-check"></i><b>4.5.2</b> filter() - Subsetting Data</a></li>
<li class="chapter" data-level="4.5.3" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#select---selecting-specific-columns"><i class="fa fa-check"></i><b>4.5.3</b> select() - Selecting specific columns</a></li>
<li class="chapter" data-level="4.5.4" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#mutate---creating-new-columns"><i class="fa fa-check"></i><b>4.5.4</b> mutate() - Creating new columns</a></li>
<li class="chapter" data-level="4.5.5" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#arrange---sort-data-columns"><i class="fa fa-check"></i><b>4.5.5</b> arrange() - Sort Data Columns</a></li>
<li class="chapter" data-level="4.5.6" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#chaining-together"><i class="fa fa-check"></i><b>4.5.6</b> Chaining together</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#wide-versus-long-data"><i class="fa fa-check"></i><b>4.6</b> Wide versus Long Data</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#wide-to-long"><i class="fa fa-check"></i><b>4.6.1</b> Wide to Long</a></li>
<li class="chapter" data-level="4.6.2" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#long-to-wide"><i class="fa fa-check"></i><b>4.6.2</b> Long to Wide</a></li>
<li class="chapter" data-level="4.6.3" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#real-data-example."><i class="fa fa-check"></i><b>4.6.3</b> Real Data Example.</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="introduction-to-data-carpentry.html"><a href="introduction-to-data-carpentry.html#joins"><i class="fa fa-check"></i><b>4.7</b> Joins</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>5</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-visualization.html"><a href="data-visualization.html#introduction-to-ggplot2"><i class="fa fa-check"></i><b>5.1</b> Introduction to ggplot2</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-visualization.html"><a href="data-visualization.html#assigning-plots"><i class="fa fa-check"></i><b>5.1.1</b> Assigning plots</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-visualization.html"><a href="data-visualization.html#titles-and-axes-titles"><i class="fa fa-check"></i><b>5.1.2</b> Titles and Axes Titles</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-visualization.html"><a href="data-visualization.html#colors-shapes-and-sizes"><i class="fa fa-check"></i><b>5.1.3</b> Colors, Shapes and Sizes</a></li>
<li class="chapter" data-level="5.1.4" data-path="data-visualization.html"><a href="data-visualization.html#themes"><i class="fa fa-check"></i><b>5.1.4</b> Themes</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-visualization.html"><a href="data-visualization.html#histograms"><i class="fa fa-check"></i><b>5.2</b> Histograms</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="data-visualization.html"><a href="data-visualization.html#histograms-with-ggplot2"><i class="fa fa-check"></i><b>5.2.1</b> Histograms with ggplot2</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-visualization.html"><a href="data-visualization.html#density-curves"><i class="fa fa-check"></i><b>5.2.2</b> Density Curves</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-visualization.html"><a href="data-visualization.html#comparing-distributions"><i class="fa fa-check"></i><b>5.2.3</b> Comparing Distributions</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-visualization.html"><a href="data-visualization.html#stem-and-leaf-plots"><i class="fa fa-check"></i><b>5.2.4</b> Stem-and-Leaf Plots</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-visualization.html"><a href="data-visualization.html#scatterplots"><i class="fa fa-check"></i><b>5.3</b> Scatterplots</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data-visualization.html"><a href="data-visualization.html#bubble-charts"><i class="fa fa-check"></i><b>5.3.1</b> Bubble Charts</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data-visualization.html"><a href="data-visualization.html#line-graphs"><i class="fa fa-check"></i><b>5.4</b> Line Graphs</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="data-visualization.html"><a href="data-visualization.html#multiple-line-graphs"><i class="fa fa-check"></i><b>5.4.1</b> Multiple Line Graphs</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="data-visualization.html"><a href="data-visualization.html#comparing-distributions-across-groups"><i class="fa fa-check"></i><b>5.5</b> Comparing Distributions across Groups</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="data-visualization.html"><a href="data-visualization.html#strip-plots"><i class="fa fa-check"></i><b>5.5.1</b> Strip Plots</a></li>
<li class="chapter" data-level="5.5.2" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>5.5.2</b> Boxplots</a></li>
<li class="chapter" data-level="5.5.3" data-path="data-visualization.html"><a href="data-visualization.html#violin-plots"><i class="fa fa-check"></i><b>5.5.3</b> Violin Plots</a></li>
<li class="chapter" data-level="5.5.4" data-path="data-visualization.html"><a href="data-visualization.html#stacked-boxplots"><i class="fa fa-check"></i><b>5.5.4</b> Stacked Boxplots</a></li>
<li class="chapter" data-level="5.5.5" data-path="data-visualization.html"><a href="data-visualization.html#ridgeline-plots"><i class="fa fa-check"></i><b>5.5.5</b> Ridgeline Plots</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="data-visualization.html"><a href="data-visualization.html#bar-graphs"><i class="fa fa-check"></i><b>5.6</b> Bar Graphs</a></li>
<li class="chapter" data-level="5.7" data-path="data-visualization.html"><a href="data-visualization.html#small-multiples"><i class="fa fa-check"></i><b>5.7</b> Small Multiples</a></li>
<li class="chapter" data-level="5.8" data-path="data-visualization.html"><a href="data-visualization.html#saving-and-exporting-ggplot2-graphs"><i class="fa fa-check"></i><b>5.8</b> Saving and Exporting ggplot2 graphs</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptives.html"><a href="descriptives.html"><i class="fa fa-check"></i><b>6</b> Descriptives</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descriptives.html"><a href="descriptives.html#sample-vs-population"><i class="fa fa-check"></i><b>6.1</b> Sample vs Population</a></li>
<li class="chapter" data-level="6.2" data-path="descriptives.html"><a href="descriptives.html#sample-and-population-size"><i class="fa fa-check"></i><b>6.2</b> Sample and Population Size</a></li>
<li class="chapter" data-level="6.3" data-path="descriptives.html"><a href="descriptives.html#central-tendency"><i class="fa fa-check"></i><b>6.3</b> Central Tendency</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="descriptives.html"><a href="descriptives.html#mode"><i class="fa fa-check"></i><b>6.3.1</b> Mode</a></li>
<li class="chapter" data-level="6.3.2" data-path="descriptives.html"><a href="descriptives.html#median"><i class="fa fa-check"></i><b>6.3.2</b> Median</a></li>
<li class="chapter" data-level="6.3.3" data-path="descriptives.html"><a href="descriptives.html#mean"><i class="fa fa-check"></i><b>6.3.3</b> Mean</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="descriptives.html"><a href="descriptives.html#variation"><i class="fa fa-check"></i><b>6.4</b> Variation</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descriptives.html"><a href="descriptives.html#range"><i class="fa fa-check"></i><b>6.4.1</b> Range</a></li>
<li class="chapter" data-level="6.4.2" data-path="descriptives.html"><a href="descriptives.html#interquartile-range"><i class="fa fa-check"></i><b>6.4.2</b> Interquartile Range</a></li>
<li class="chapter" data-level="6.4.3" data-path="descriptives.html"><a href="descriptives.html#average-deviation"><i class="fa fa-check"></i><b>6.4.3</b> Average Deviation</a></li>
<li class="chapter" data-level="6.4.4" data-path="descriptives.html"><a href="descriptives.html#standard-deviation"><i class="fa fa-check"></i><b>6.4.4</b> Standard Deviation</a></li>
<li class="chapter" data-level="6.4.5" data-path="descriptives.html"><a href="descriptives.html#variance"><i class="fa fa-check"></i><b>6.4.5</b> Variance</a></li>
<li class="chapter" data-level="6.4.6" data-path="descriptives.html"><a href="descriptives.html#average-versus-standard-deviation"><i class="fa fa-check"></i><b>6.4.6</b> Average versus Standard Deviation</a></li>
<li class="chapter" data-level="6.4.7" data-path="descriptives.html"><a href="descriptives.html#sample-standard-deviation"><i class="fa fa-check"></i><b>6.4.7</b> Sample Standard Deviation</a></li>
<li class="chapter" data-level="6.4.8" data-path="descriptives.html"><a href="descriptives.html#sample-versus-population-standard-deviation"><i class="fa fa-check"></i><b>6.4.8</b> Sample versus Population Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="descriptives.html"><a href="descriptives.html#descriptive-statistics-in-r"><i class="fa fa-check"></i><b>6.5</b> Descriptive Statistics in R</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="descriptives.html"><a href="descriptives.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>6.5.1</b> Dealing with Missing Data</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="descriptives.html"><a href="descriptives.html#descriptives-for-datasets"><i class="fa fa-check"></i><b>6.6</b> Descriptives for Datasets</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="descriptives.html"><a href="descriptives.html#descriptives-for-groups"><i class="fa fa-check"></i><b>6.6.1</b> Descriptives for Groups</a></li>
<li class="chapter" data-level="6.6.2" data-path="descriptives.html"><a href="descriptives.html#counts-by-group"><i class="fa fa-check"></i><b>6.6.2</b> Counts by Group</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="distributions.html"><a href="distributions.html"><i class="fa fa-check"></i><b>7</b> Distributions</a>
<ul>
<li class="chapter" data-level="7.0.1" data-path="distributions.html"><a href="distributions.html#uniform-distribution"><i class="fa fa-check"></i><b>7.0.1</b> Uniform Distribution</a></li>
<li class="chapter" data-level="7.0.2" data-path="distributions.html"><a href="distributions.html#bimodal-distribution"><i class="fa fa-check"></i><b>7.0.2</b> Bimodal Distribution</a></li>
<li class="chapter" data-level="7.0.3" data-path="distributions.html"><a href="distributions.html#normal-distribution"><i class="fa fa-check"></i><b>7.0.3</b> Normal Distribution</a></li>
<li class="chapter" data-level="7.0.4" data-path="distributions.html"><a href="distributions.html#standard-normal-distribution"><i class="fa fa-check"></i><b>7.0.4</b> Standard Normal Distribution</a></li>
<li class="chapter" data-level="7.0.5" data-path="distributions.html"><a href="distributions.html#skewness-and-kurtosis"><i class="fa fa-check"></i><b>7.0.5</b> Skewness and Kurtosis</a></li>
<li class="chapter" data-level="7.1" data-path="distributions.html"><a href="distributions.html#z-scores"><i class="fa fa-check"></i><b>7.1</b> Z-scores</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="distributions.html"><a href="distributions.html#z-scores-in-samples."><i class="fa fa-check"></i><b>7.1.1</b> z-scores in samples.</a></li>
<li class="chapter" data-level="7.1.2" data-path="distributions.html"><a href="distributions.html#using-z-scores-to-determine-probabilities"><i class="fa fa-check"></i><b>7.1.2</b> Using z-scores to determine probabilities</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="distributions.html"><a href="distributions.html#what-is-a-sampling-distribution"><i class="fa fa-check"></i><b>7.2</b> What is a Sampling Distribution ?</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="distributions.html"><a href="distributions.html#sample-size-and-the-sampling-distribution"><i class="fa fa-check"></i><b>7.2.1</b> Sample Size and the Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="distributions.html"><a href="distributions.html#central-limit-theorem"><i class="fa fa-check"></i><b>7.3</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="7.4" data-path="distributions.html"><a href="distributions.html#sampling-distribution-problems"><i class="fa fa-check"></i><b>7.4</b> Sampling distribution problems</a></li>
<li class="chapter" data-level="7.5" data-path="distributions.html"><a href="distributions.html#the-t-distribution"><i class="fa fa-check"></i><b>7.5</b> The t-distribution</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>8</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="8.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#sample-means-as-estimates."><i class="fa fa-check"></i><b>8.1</b> Sample means as estimates.</a></li>
<li class="chapter" data-level="8.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-a-confidence-interval-with-z-distribution"><i class="fa fa-check"></i><b>8.2</b> Calculating a confidence interval with z-distribution</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#other-confidence-intervals-ranges"><i class="fa fa-check"></i><b>8.2.1</b> Other Confidence Intervals ranges</a></li>
<li class="chapter" data-level="8.2.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-intervals-and-sample-size"><i class="fa fa-check"></i><b>8.2.2</b> Confidence Intervals and Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="confidence-intervals.html"><a href="confidence-intervals.html#confidence-intervals-with-t-distribution"><i class="fa fa-check"></i><b>8.3</b> Confidence Intervals with t-distribution</a></li>
<li class="chapter" data-level="8.4" data-path="confidence-intervals.html"><a href="confidence-intervals.html#calculating-a-t-distribution-confidence-interval"><i class="fa fa-check"></i><b>8.4</b> Calculating a t-distribution Confidence Interval</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="confidence-intervals.html"><a href="confidence-intervals.html#t-distribution-cis-and-sample-size."><i class="fa fa-check"></i><b>8.4.1</b> t-distribution CIs and sample size.</a></li>
<li class="chapter" data-level="8.4.2" data-path="confidence-intervals.html"><a href="confidence-intervals.html#other-confidence-intervals-ranges-for-t-distribution"><i class="fa fa-check"></i><b>8.4.2</b> Other Confidence Intervals ranges for t-distribution</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="confidence-intervals.html"><a href="confidence-intervals.html#comparing-cis-using-the-z--and-t-distributions"><i class="fa fa-check"></i><b>8.5</b> Comparing CIs using the z- and t-distributions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html"><i class="fa fa-check"></i><b>9</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="9.1" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#two-tailed-and-one-tailed-tests"><i class="fa fa-check"></i><b>9.1</b> Two-tailed and One-tailed tests</a></li>
<li class="chapter" data-level="9.2" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#examples-of-1--and-2-tailed-tests"><i class="fa fa-check"></i><b>9.2</b> Examples of 1- and 2-tailed tests</a></li>
<li class="chapter" data-level="9.3" data-path="hypothesis-testing.html"><a href="hypothesis-testing.html#significance-levels-and-p-values"><i class="fa fa-check"></i><b>9.3</b> Significance Levels and p-values</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html"><i class="fa fa-check"></i><b>10</b> One Sample Inferential Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#one-sample-z-tests"><i class="fa fa-check"></i><b>10.1</b> One-sample z-tests</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#sampling-distribution-recap"><i class="fa fa-check"></i><b>10.1.1</b> Sampling Distribution Recap</a></li>
<li class="chapter" data-level="10.1.2" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#calculating-p-values-for-z-test"><i class="fa fa-check"></i><b>10.1.2</b> Calculating p-values for z-test</a></li>
<li class="chapter" data-level="10.1.3" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#using-critical-values"><i class="fa fa-check"></i><b>10.1.3</b> Using critical values</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#one-sample-t-tests"><i class="fa fa-check"></i><b>10.2</b> One-sample t-tests</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#critical-values-for-the-one-sample-t-test"><i class="fa fa-check"></i><b>10.2.1</b> Critical values for the one-sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#conducting-one-sample-t-tests-in-r"><i class="fa fa-check"></i><b>10.3</b> Conducting one-sample t-tests in R</a></li>
<li class="chapter" data-level="10.4" data-path="one-sample-inferential-statistics.html"><a href="one-sample-inferential-statistics.html#assumptions-of-the-one-sample-t-test"><i class="fa fa-check"></i><b>10.4</b> Assumptions of the one-sample t-test</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html"><i class="fa fa-check"></i><b>11</b> Two Sample Inferential Statistics</a>
<ul>
<li class="chapter" data-level="11.1" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#independent-samples-t-test"><i class="fa fa-check"></i><b>11.1</b> Independent Samples t-test</a></li>
<li class="chapter" data-level="11.2" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#sampling-distribution-of-the-difference-in-sample-means"><i class="fa fa-check"></i><b>11.2</b> Sampling Distribution of the Difference in Sample Means</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#visualizing-the-sampling-distribution"><i class="fa fa-check"></i><b>11.2.1</b> Visualizing the Sampling Distribution</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#pooled-standard-deviation"><i class="fa fa-check"></i><b>11.3</b> Pooled Standard Deviation</a></li>
<li class="chapter" data-level="11.4" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#theory-behind-students-t-test"><i class="fa fa-check"></i><b>11.4</b> Theory behind Student’s t-test</a></li>
<li class="chapter" data-level="11.5" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#confidence-interval-for-difference-in-means"><i class="fa fa-check"></i><b>11.5</b> Confidence Interval for Difference in Means</a></li>
<li class="chapter" data-level="11.6" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#conducting-the-student-t-test-in-r"><i class="fa fa-check"></i><b>11.6</b> Conducting the Student t-test in R</a></li>
<li class="chapter" data-level="11.7" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#assumptions-of-the-independent-t-test"><i class="fa fa-check"></i><b>11.7</b> Assumptions of the Independent t-test</a></li>
<li class="chapter" data-level="11.8" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#welchs-t-test"><i class="fa fa-check"></i><b>11.8</b> Welch’s t-test</a></li>
<li class="chapter" data-level="11.9" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#effect-size-for-independent-two-sample-t-tests"><i class="fa fa-check"></i><b>11.9</b> Effect Size for Independent two sample t-tests:</a></li>
<li class="chapter" data-level="11.10" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#paired-t-tests"><i class="fa fa-check"></i><b>11.10</b> Paired t-tests</a>
<ul>
<li class="chapter" data-level="11.10.1" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#the-paired-t-test-is-a-one-sample-t-test"><i class="fa fa-check"></i><b>11.10.1</b> The paired t-test is a one-sample t-test</a></li>
<li class="chapter" data-level="11.10.2" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#one-tailed-paired-t-tests"><i class="fa fa-check"></i><b>11.10.2</b> One-tailed paired t-tests</a></li>
<li class="chapter" data-level="11.10.3" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#calculating-effect-sizes"><i class="fa fa-check"></i><b>11.10.3</b> Calculating effect sizes</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#non-parametric-alternatives-for-independent-t-tests"><i class="fa fa-check"></i><b>11.11</b> Non-parametric Alternatives for Independent t-tests</a></li>
<li class="chapter" data-level="11.12" data-path="two-sample-inferential-statistics.html"><a href="two-sample-inferential-statistics.html#non-parametric-alternatives-to-the-two-sample-t-tests"><i class="fa fa-check"></i><b>11.12</b> Non-parametric Alternatives to the Two Sample t-tests</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>12</b> Correlation</a>
<ul>
<li class="chapter" data-level="12.1" data-path="correlation.html"><a href="correlation.html#pearson-correlation"><i class="fa fa-check"></i><b>12.1</b> Pearson Correlation</a></li>
<li class="chapter" data-level="12.2" data-path="correlation.html"><a href="correlation.html#cross-products"><i class="fa fa-check"></i><b>12.2</b> Cross-products</a></li>
<li class="chapter" data-level="12.3" data-path="correlation.html"><a href="correlation.html#conducting-a-pearson-correlation-test"><i class="fa fa-check"></i><b>12.3</b> Conducting a Pearson Correlation Test</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="correlation.html"><a href="correlation.html#significance-testing-a-pearson-correlation"><i class="fa fa-check"></i><b>12.3.1</b> Significance Testing a Pearson Correlation</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="correlation.html"><a href="correlation.html#assumptions-of-pearsons-correlation"><i class="fa fa-check"></i><b>12.4</b> Assumptions of Pearson’s Correlation</a></li>
<li class="chapter" data-level="12.5" data-path="correlation.html"><a href="correlation.html#confidence-intervals-for-r"><i class="fa fa-check"></i><b>12.5</b> Confidence Intervals for r</a></li>
<li class="chapter" data-level="12.6" data-path="correlation.html"><a href="correlation.html#partial-correlations"><i class="fa fa-check"></i><b>12.6</b> Partial Correlations</a></li>
<li class="chapter" data-level="12.7" data-path="correlation.html"><a href="correlation.html#non-parametric-correlations"><i class="fa fa-check"></i><b>12.7</b> Non-parametric Correlations</a></li>
<li class="chapter" data-level="12.8" data-path="correlation.html"><a href="correlation.html#point-biserial-correlation"><i class="fa fa-check"></i><b>12.8</b> Point-Biserial Correlation</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>13</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="13.1" data-path="linear-regression.html"><a href="linear-regression.html#introduction-to-linear-regression"><i class="fa fa-check"></i><b>13.1</b> Introduction to Linear Regression</a></li>
<li class="chapter" data-level="13.2" data-path="linear-regression.html"><a href="linear-regression.html#a-and-b"><i class="fa fa-check"></i><b>13.2</b> a and b</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="linear-regression.html"><a href="linear-regression.html#how-to-calculate-a-and-b-in-r"><i class="fa fa-check"></i><b>13.2.1</b> How to calculate a and b in R</a></li>
<li class="chapter" data-level="13.2.2" data-path="linear-regression.html"><a href="linear-regression.html#how-to-calculate-a-and-b-by-hand"><i class="fa fa-check"></i><b>13.2.2</b> How to calculate a and b ‘by hand’</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="linear-regression.html"><a href="linear-regression.html#residuals"><i class="fa fa-check"></i><b>13.3</b> Residuals</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="linear-regression.html"><a href="linear-regression.html#how-to-calculate-the-residuals"><i class="fa fa-check"></i><b>13.3.1</b> How to calculate the residuals</a></li>
<li class="chapter" data-level="13.3.2" data-path="linear-regression.html"><a href="linear-regression.html#visualizing-the-residuals"><i class="fa fa-check"></i><b>13.3.2</b> Visualizing the Residuals</a></li>
<li class="chapter" data-level="13.3.3" data-path="linear-regression.html"><a href="linear-regression.html#comparing-our-trendline-to-other-trendlines"><i class="fa fa-check"></i><b>13.3.3</b> Comparing our trendline to other trendlines</a></li>
<li class="chapter" data-level="13.3.4" data-path="linear-regression.html"><a href="linear-regression.html#coefficient-of-determination-r2"><i class="fa fa-check"></i><b>13.3.4</b> Coefficient of Determination R2</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="linear-regression.html"><a href="linear-regression.html#standard-error-of-the-estimate"><i class="fa fa-check"></i><b>13.4</b> Standard Error of the Estimate</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="linear-regression.html"><a href="linear-regression.html#what-to-do-with-the-standard-error-of-the-estimate"><i class="fa fa-check"></i><b>13.4.1</b> What to do with the Standard Error of the Estimate ?</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="linear-regression.html"><a href="linear-regression.html#goodness-of-fit-test---f-ratio"><i class="fa fa-check"></i><b>13.5</b> Goodness of Fit Test - F-ratio</a></li>
<li class="chapter" data-level="13.6" data-path="linear-regression.html"><a href="linear-regression.html#assumptions-of-linear-regression"><i class="fa fa-check"></i><b>13.6</b> Assumptions of Linear Regression</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="linear-regression.html"><a href="linear-regression.html#normality-of-residuals"><i class="fa fa-check"></i><b>13.6.1</b> Normality of Residuals</a></li>
<li class="chapter" data-level="13.6.2" data-path="linear-regression.html"><a href="linear-regression.html#linearity"><i class="fa fa-check"></i><b>13.6.2</b> 2. Linearity —</a></li>
<li class="chapter" data-level="13.6.3" data-path="linear-regression.html"><a href="linear-regression.html#homogeneity-of-variance-homoscedasticity"><i class="fa fa-check"></i><b>13.6.3</b> 3. Homogeneity of Variance / Homoscedasticity</a></li>
<li class="chapter" data-level="13.6.4" data-path="linear-regression.html"><a href="linear-regression.html#no-colinearity"><i class="fa fa-check"></i><b>13.6.4</b> No Colinearity</a></li>
<li class="chapter" data-level="13.6.5" data-path="linear-regression.html"><a href="linear-regression.html#unusual-datapoints"><i class="fa fa-check"></i><b>13.6.5</b> Unusual Datapoints</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="linear-regression.html"><a href="linear-regression.html#examining-individual-predictor-estimates"><i class="fa fa-check"></i><b>13.7</b> Examining individual predictor estimates</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="linear-regression.html"><a href="linear-regression.html#confidence-interval-of-b."><i class="fa fa-check"></i><b>13.7.1</b> 95% confidence interval of ‘b’.</a></li>
<li class="chapter" data-level="13.7.2" data-path="linear-regression.html"><a href="linear-regression.html#standard-error-of-b"><i class="fa fa-check"></i><b>13.7.2</b> Standard Error of b</a></li>
<li class="chapter" data-level="13.7.3" data-path="linear-regression.html"><a href="linear-regression.html#calculating-95-confidence-interval-of-b-by-hand"><i class="fa fa-check"></i><b>13.7.3</b> Calculating 95% confidence interval of ‘b’ by hand</a></li>
<li class="chapter" data-level="13.7.4" data-path="linear-regression.html"><a href="linear-regression.html#signifcance-testing-b"><i class="fa fa-check"></i><b>13.7.4</b> Signifcance Testing b</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="permutation-testing.html"><a href="permutation-testing.html"><i class="fa fa-check"></i><b>14</b> Permutation Testing</a>
<ul>
<li class="chapter" data-level="14.1" data-path="permutation-testing.html"><a href="permutation-testing.html#t-test-permutation"><i class="fa fa-check"></i><b>14.1</b> t-test Permutation</a></li>
<li class="chapter" data-level="14.2" data-path="permutation-testing.html"><a href="permutation-testing.html#correlation-coefficient-permutation-tests"><i class="fa fa-check"></i><b>14.2</b> Correlation Coefficient Permutation Tests</a></li>
<li class="chapter" data-level="14.3" data-path="permutation-testing.html"><a href="permutation-testing.html#permutation-test-for-a-paired-t-test"><i class="fa fa-check"></i><b>14.3</b> Permutation test for a Paired t-test</a></li>
<li class="chapter" data-level="14.4" data-path="permutation-testing.html"><a href="permutation-testing.html#permutation-tests-in-packages"><i class="fa fa-check"></i><b>14.4</b> Permutation tests in Packages</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="analyzing-categorical-data.html"><a href="analyzing-categorical-data.html"><i class="fa fa-check"></i><b>15</b> Analyzing Categorical Data</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSY317L &amp; PSY120R Textbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptives" class="section level1" number="6">
<h1><span class="header-section-number">Chapter 6</span> Descriptives</h1>
<p>Descriptive statistics describe basic features of the data in simple summaries. Examples include reporting measures of <strong>central tendency</strong> such as the mean, median, and mode. These are values that represent the most typical or most central point of a data distribution. Another class of descriptives are measures of <strong>variability</strong> or <strong>variation</strong> such as variance, standard deviation, ranges or interquartile ranges. These measures describe the spread of data. As well as being useful summaries in their own right, descriptive statistics are also used in data visualization to summarize distributions. There are several functions in R and other packages that help to get descriptive statistics from data. Before we go into detail about how to use R to get descriptives, we’ll describe these measures of central tendency and variation in a bit more detail.</p>
<div id="sample-vs-population" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> Sample vs Population</h2>
<p>The first thing we would like to discuss is the difference between <strong>samples</strong> and <strong>populations</strong>. We can calculate descriptive measures such as means and standard deviations for both samples and populations, but we use different notation to describe these. A population is all subjects that we could possibly collect data from. For example, if we were interested in the IQ scores of eighth graders in Texas, then our population of interest is all eighth graders in Texas. If we wished to study maze learning in juvenile rats, then our population of interest would be all juvenile rats. If we were studying leaf growth in sunflowers, then our population of interest is all sunflowers. If we were able to measure the size of leaves on all sunflowers in existence, or measure the maze learning of all juvenile rats in the world, or the IQ of all eighth graders in Texas, then we would have data for the whole population. We would then be able to say something about the mean or median or some other descriptive about the population. Clearly, it is not always possible to measure every subject in a population. Of our three examples, it may just about be possible to measure the IQ of all Texas eighth graders although it would be a lot of work. It seems unlikely to be possible to measure the leaf growth of all sunflowers or the maze learning of all juvenile rats. Instead, what we typically do is to collect data on a subset of subjects. We call this subset a <strong>sample</strong>. For instance, if we picked 10 sunflowers then we would collect data on just those sunflowers. We may be able to calculate the average leaf size of these 10 sunflowers and use that to <strong>estimate</strong> what the true leaf size is of all sunflowers. We call the descriptive measures of samples <strong>estimates</strong> or <strong>statistics</strong>, whereas the descriptive measures of populations are called <strong>parameters</strong>.</p>
<p>Let’s now discuss different descriptive measures in turn.</p>
</div>
<div id="sample-and-population-size" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Sample and Population Size</h2>
<p>This isn’t strictly a descriptive measure - but it is worth pointing out that the notation for the size of your data is different depending upon whether you are talking about a sample of a population. If you are taking about a sample, then we use the lower case <span class="math inline">\(n\)</span> to refer to the sample size. So, if you see <span class="math inline">\(n=10\)</span> this means that the sample size is 10. e.g. you picked 10 sunflowers to collect data on. If you see the upper case <span class="math inline">\(N\)</span> this refers to the population size. So if you see that the population size is <span class="math inline">\(N=1200000\)</span> this refers to a population size of 1.2 million.</p>
</div>
<div id="central-tendency" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Central Tendency</h2>
<p>The first class of descriptives we will explore are measures of central tendency. These can be thought of as values that describe what is the most common, most typical or most average value in a distribution. Also, here we are using the term <strong>distribution</strong> to refer to a group of numbers or our data.</p>
<p>We’ll use the following dataset as an example. Let’s imagine that this is a sample of data:</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="descriptives.html#cb540-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">14</span>, <span class="dv">12</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">11</span>, <span class="dv">15</span>, <span class="dv">9</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">11</span>)</span>
<span id="cb540-2"><a href="descriptives.html#cb540-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div>
<pre><code>##  [1]  1 14 12  5  3  6 11 15  9  5  4  2  7  5  3  8 11</code></pre>
<p>We can calculate the sample size using <code>length()</code>:</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="descriptives.html#cb542-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(x)</span></code></pre></div>
<pre><code>## [1] 17</code></pre>
<p>We can see that the sample size is <span class="math inline">\(n=17\)</span>.</p>
<div id="mode" class="section level3" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Mode</h3>
<p>The <strong>mode</strong> or <strong>modal value</strong> of a distribution is the most frequent or most common value in a distribution. The number that appears the most times in our sample of data above is <code>5</code>. The mode is therefore 5. In our example, it’s possible to manually check all the values, but a quicker way to summarize the frequency count of each value in a vector in R is to use <code>table()</code> like this:</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="descriptives.html#cb544-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(x)</span></code></pre></div>
<pre><code>## x
##  1  2  3  4  5  6  7  8  9 11 12 14 15 
##  1  1  2  1  3  1  1  1  1  2  1  1  1</code></pre>
<p>We can see that there are 3 instances of the number 5 making it the mode. There are two instances of 11 and 3, and every other number in the distribution has only 1 instance.</p>
<p>Is 5 really the ‘middle’ of this distribution though? The mode has some serious deficiencies as a measure of central tendency in that although it picks up on the most frequent value, that value isn’t necessarily the most central measure.</p>
</div>
<div id="median" class="section level3" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Median</h3>
<p>The median value is the <strong>middle</strong> value of the distribution. It represents the value at which 50% of the data lies above the median, and 50% lies below the data.</p>
<p>One way to look at this is to visualize our distribution as a dot plot:</p>
<p><img src="img/des1.png" /></p>
<p>We have 17 datapoints, which is an odd number. In this case, we want the number/dot at which half the remaining datapoints (8) are below the median, and half (the other 8) are above the median. You can see in the image, that the median value is therefore 6. This leaves 8 dots below it and 8 dots above it.</p>
<p>To do this by hand, we would first order the data, and then work from the outside to the inside of the distribution, crossing off one from each end at a time. The image below shows how we’re doing that using different colors to show the crossing out:</p>
<p><img src="img/des2.png" /></p>
<p>In R, we have a quick shortcut for calculating the median, and it’s to use the function called <code>median()</code>:</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="descriptives.html#cb546-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(x)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>If we have an even number of values in our distribution, then we take the average of the middle two values. For example, look at the image below. It has 12 numbers in the distribution, so we take the average of the 6th and 7th number:</p>
<p><img src="img/des3.png" /></p>
<p>Once we’ve crossed out each number going from outside to in, we’re left with the 6th and 7th numbers being 10 and 15. The average of these numbers is 12.5, so the median is 12.5. We can see that with <code>median()</code>:</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="descriptives.html#cb548-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">16</span>,<span class="dv">16</span>,<span class="dv">21</span>,<span class="dv">21</span>,<span class="dv">22</span>)</span>
<span id="cb548-2"><a href="descriptives.html#cb548-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(y)</span></code></pre></div>
<pre><code>## [1] 12.5</code></pre>
</div>
<div id="mean" class="section level3" number="6.3.3">
<h3><span class="header-section-number">6.3.3</span> Mean</h3>
<p>The mean, or <strong>arithmetic mean</strong> is the measure that most people think about when they think of the <em>average</em> value in a dataset or distribution. There are actually various different ways of calculating means, so the one that we will focus on is called the arithmetic mean. This is calculated by adding up all the numbers in a distribution and then dividing by the number of datapoints. You can write this as a formula. For a sample, it looks like this:</p>
<p><span class="math inline">\(\overline{x} = \frac{\Sigma{x}}{n}\)</span></p>
<p>And for a population it looks like this:</p>
<p><span class="math inline">\(\mu = \frac{\Sigma{x}}{N}\)</span></p>
<p>Notice that we use <span class="math inline">\(\overline{x}\)</span> to denote the mean of a sample, and <span class="math inline">\(\mu\)</span> to denote the mean of a population. Despite these notation differences, the formula is essentially exactly the same.</p>
<p>Let’s calculate the arithmetic mean of our distribution <code>x</code>:</p>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="descriptives.html#cb550-1" aria-hidden="true" tabindex="-1"></a>sum_of_x <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">14</span> <span class="sc">+</span> <span class="dv">12</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">+</span> <span class="dv">6</span> <span class="sc">+</span> <span class="dv">11</span> <span class="sc">+</span> <span class="dv">15</span> <span class="sc">+</span> <span class="dv">9</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">4</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">7</span> <span class="sc">+</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">+</span> <span class="dv">8</span> <span class="sc">+</span> <span class="dv">11</span></span>
<span id="cb550-2"><a href="descriptives.html#cb550-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb550-3"><a href="descriptives.html#cb550-3" aria-hidden="true" tabindex="-1"></a>sum_of_x</span></code></pre></div>
<pre><code>## [1] 121</code></pre>
<p>So, here <span class="math inline">\(\Sigma{x}=121\)</span>. That makes the mean:</p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="descriptives.html#cb552-1" aria-hidden="true" tabindex="-1"></a>sum_of_x <span class="sc">/</span> <span class="dv">17</span></span></code></pre></div>
<pre><code>## [1] 7.117647</code></pre>
<p>This makes the mean <span class="math inline">\(\overline{x}=7.12\)</span>. The shortcut way of doing this in R, is to use the function <code>mean()</code>:</p>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="descriptives.html#cb554-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] 7.117647</code></pre>
<p>We’ll talk more about the pros and cons of the mean and median in future chapters.</p>
</div>
</div>
<div id="variation" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Variation</h2>
<p>As well as describing the central tendency of data distributions, the other key way in which we should describe a distribution is to summarize the <strong>variation</strong> in data. This family of measures look at how much <strong>spread</strong> there is in the data. Another way of thinking about this is that these measure give us a sense of how <em>clumped</em> or how <em>spread out</em> the data are.</p>
<div id="range" class="section level3" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Range</h3>
<p>The simplest measure of spread is the <strong>range</strong>. This simply is the difference between the minimum and maximum value in a dataset. Looking at our distribution <code>x</code>, the minimum value is 1, and the maximum value is 15 - therefore the range is <span class="math inline">\(15-1 = 14\)</span>.</p>
<p><img src="img/des4.png" /></p>
<p>The problem with range as a measure can be illustrated by just adjusting our data distribution slightly. Say, instead of having a datapoint at 15, we had a value at 25. Now the range is 24 instead of 14. This suggests that the data is much more spread out, but in reality it is just one datapoint that is forcing the range to be much higher - the rest of the data is no more clumped or spread out. This is the major drawback of the range - it can be easily influenced by outliers - as illustrated below.</p>
<p><img src="img/des5.png" /></p>
<p>In R, we can calculate the minimum, maximum and range of a distribution using the functions <code>min()</code>, <code>max()</code> and <code>range()</code>. Although <code>range()</code> just gives us the minimum and maximum values, we have to do the rest:</p>
<div class="sourceCode" id="cb556"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb556-1"><a href="descriptives.html#cb556-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(x)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb558"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb558-1"><a href="descriptives.html#cb558-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(x)</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="descriptives.html#cb560-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(x)</span></code></pre></div>
<pre><code>## [1]  1 15</code></pre>
</div>
<div id="interquartile-range" class="section level3" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Interquartile Range</h3>
<p>The interquartile range or IQR is another measure of spread. It is roughly equivalent to the range of the middle 50% of the data. One way to think about this is to consider how the median splits the data into a bottom half and a top half. Then, calculate the median of the lower half of the data and the median of the upper half of the data. These values can be considered to be the lower quartile and upper quartile respectively. The interquartile range is the difference between these values. A visualization of this is below:</p>
<p><img src="img/des6.png" /></p>
<p>The median of the bottom half of our data is 3.5 (the average of 3 and 4). The median of the top half is 11 (the average of 11 and 11). This makes the IQR equal to <span class="math inline">\(11-3.5 = 7.5\)</span>.</p>
<p>If we start with an even number of numbers in our distribution, then we include each of the middle numbers in their respective lower and upper halves. The image below represents this:</p>
<p><img src="img/des7.png" /></p>
<p>With this distribution, we calculated the median to be 12.5 as the numbers 10 and 15th were the middle two values. Because of this, we include 10 in the bottom half and 15 in the top half. When we work out to in on each of these halves, we find that the median of the bottom half is 8 (the average of 7 and 9) and the median of the upper half is 18.5 (the average of 16 and 21). Therefore, the lower quartile is 8 and the upper quartile is 18.5, making the IQR equal to <span class="math inline">\(18.5-8=10.5\)</span>.</p>
<p>The above explanation of how to calculate the IQR is actually just one way of trying to estimate the “middle 50%” of the data. With this way of doing it, the lower quartile represents the 25% percentile of the data (25% of values being lower than it and 75% of values being higher). The upper quartile represents the 75% percentile of the data (75% of values being lower than it and 25% being higher).</p>
<p>Unfortunately, there are several ways of calculating the lower and upper quartiles and estimating where these 25% and 75% percentiles are. When we calculate them in R, the default method it uses is actually different to our ‘by hand’ method. To calculate quartiles, we use the function <code>quantile()</code> (note - not quartile!) but we have to put a second argument to say if we want the lower quartile or upper quartile.</p>
<div class="sourceCode" id="cb562"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb562-1"><a href="descriptives.html#cb562-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(x, <span class="fl">0.25</span>) <span class="co">#0.25 means lower quartile</span></span></code></pre></div>
<pre><code>## 25% 
##   4</code></pre>
<div class="sourceCode" id="cb564"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb564-1"><a href="descriptives.html#cb564-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(x, <span class="fl">0.75</span>) <span class="co">#0.75 means upper quartile</span></span></code></pre></div>
<pre><code>## 75% 
##  11</code></pre>
<p>You can see these values are slightly different to our ‘by hand’ method. The upper quartile of <code>x</code> agrees with our method being 11. By hand we got the lower quartile to be 3.5, but R gives it as 4. This would make the IQR equal to <span class="math inline">\(11-4 =7\)</span>. The quick way of getting that in R is to use <code>IQR()</code>:</p>
<div class="sourceCode" id="cb566"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb566-1"><a href="descriptives.html#cb566-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(x)</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>We recommend using the R functions to calculate quartiles and interquartile ranges - it is a slightly stronger method than our by-hand method. You can actually do the by-hand method in R by adding <code>type=6</code> to the functions. There are actually nine different ways of calculating these in R - which is ridiculous!</p>
<div class="sourceCode" id="cb568"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb568-1"><a href="descriptives.html#cb568-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(x, <span class="fl">0.25</span>, <span class="at">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## 25% 
## 3.5</code></pre>
<div class="sourceCode" id="cb570"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb570-1"><a href="descriptives.html#cb570-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(x, <span class="fl">0.75</span>, <span class="at">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## 75% 
##  11</code></pre>
<div class="sourceCode" id="cb572"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb572-1"><a href="descriptives.html#cb572-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(x, <span class="at">type =</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 7.5</code></pre>
</div>
<div id="average-deviation" class="section level3" number="6.4.3">
<h3><span class="header-section-number">6.4.3</span> Average Deviation</h3>
<p>An alternative way of looking at spread is to ask how far from the center of the data distribution (i.e. the mean) is each datapoint on average. Distributions that are highly clumped will have most datapoints very close to the distribution’s mean. Distributions that are spread out will have several datapoints that are far away from the mean.</p>
<p>Look at the two distributions below. Both of them have means of 10. The top distribution (A) however is much more clumped than the bottom distribution (B) which is more spread out.</p>
<p><img src="img/des8.png" /></p>
<p>Let’s look at these in more detail. We’ll start with distribution A. We can calculate the difference of each datapoint from the mean (10) like this:</p>
<div class="sourceCode" id="cb574"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb574-1"><a href="descriptives.html#cb574-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>,<span class="dv">12</span>,<span class="dv">12</span>,<span class="dv">14</span>)</span>
<span id="cb574-2"><a href="descriptives.html#cb574-2" aria-hidden="true" tabindex="-1"></a>A <span class="sc">-</span> <span class="fu">mean</span>(A)</span></code></pre></div>
<pre><code>##  [1] -5 -2 -2 -1 -1  0  0  1  2  2  2  4</code></pre>
<p>If we add up all of those differences from the mean, then they will equal 0. We can show this like this:</p>
<div class="sourceCode" id="cb576"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb576-1"><a href="descriptives.html#cb576-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(A <span class="sc">-</span> <span class="fu">mean</span>(A))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>A way to count up all the differences from the mean and to make sure that they count is to make each number positive regardless of its sign. We can do this using <code>abs()</code> in R:</p>
<div class="sourceCode" id="cb578"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb578-1"><a href="descriptives.html#cb578-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(A <span class="sc">-</span> <span class="fu">mean</span>(A))</span></code></pre></div>
<pre><code>##  [1] 5 2 2 1 1 0 0 1 2 2 2 4</code></pre>
<p>When we sum all of these values up, we get the total of all the differences from the mean of each datapoint:</p>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="descriptives.html#cb580-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(A <span class="sc">-</span> <span class="fu">mean</span>(A)))</span></code></pre></div>
<pre><code>## [1] 22</code></pre>
<p>We see that this total is 22. In formula notation, we find that <span class="math inline">\(\Sigma|(x - \overline{\mu})|\)</span>. Here <span class="math inline">\(x\)</span> represents each datapoint. <span class="math inline">\(\overline{\mu}\)</span> represents the population mean. <span class="math inline">\(| |\)</span> represents ‘take the absolute values of’, and <span class="math inline">\(\Sigma\)</span> means “sum up”.</p>
<p>To get the “average deviation” we simply divide our sum of difference scores by the number of datapoints, which is 12 in this case. The formula for average deviation is:</p>
<p><span class="math inline">\(AD = \frac{\Sigma|(x - \overline{\mu})|}{N}\)</span></p>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="descriptives.html#cb582-1" aria-hidden="true" tabindex="-1"></a><span class="dv">22</span><span class="sc">/</span><span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 1.833333</code></pre>
<p>Our average deviation is therefore 1.83. This can be interpreted as each datapoint being on average 1.83 units away from the mean of 10.</p>
<p>Another way to have got the <span class="math inline">\(N\)</span> would have been to use <code>length()</code> which counts the number of datapoints:</p>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb584-1"><a href="descriptives.html#cb584-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(A <span class="sc">-</span> <span class="fu">mean</span>(A))) <span class="sc">/</span> <span class="fu">length</span>(A)</span></code></pre></div>
<pre><code>## [1] 1.833333</code></pre>
<p>We could do the same for distribution B. Calculate the sum of all the difference scores, and then divide by the <span class="math inline">\(N\)</span>:</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="descriptives.html#cb586-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>,<span class="dv">13</span>,<span class="dv">15</span>,<span class="dv">17</span>,<span class="dv">19</span>)</span>
<span id="cb586-2"><a href="descriptives.html#cb586-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb586-3"><a href="descriptives.html#cb586-3" aria-hidden="true" tabindex="-1"></a><span class="co">#difference scores</span></span>
<span id="cb586-4"><a href="descriptives.html#cb586-4" aria-hidden="true" tabindex="-1"></a>B <span class="sc">-</span> <span class="fu">mean</span>(B)</span></code></pre></div>
<pre><code>##  [1] -8 -7 -6 -4 -2  0  1  2  3  5  7  9</code></pre>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="descriptives.html#cb588-1" aria-hidden="true" tabindex="-1"></a><span class="co"># absolute difference scores</span></span>
<span id="cb588-2"><a href="descriptives.html#cb588-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abs</span>(B <span class="sc">-</span> <span class="fu">mean</span>(B))</span></code></pre></div>
<pre><code>##  [1] 8 7 6 4 2 0 1 2 3 5 7 9</code></pre>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="descriptives.html#cb590-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sum of absolute difference scores</span></span>
<span id="cb590-2"><a href="descriptives.html#cb590-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(B <span class="sc">-</span> <span class="fu">mean</span>(B)))</span></code></pre></div>
<pre><code>## [1] 54</code></pre>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="descriptives.html#cb592-1" aria-hidden="true" tabindex="-1"></a><span class="co"># average deviation</span></span>
<span id="cb592-2"><a href="descriptives.html#cb592-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(B <span class="sc">-</span> <span class="fu">mean</span>(B))) <span class="sc">/</span> <span class="fu">length</span>(B)</span></code></pre></div>
<pre><code>## [1] 4.5</code></pre>
<p>Here, the total sum of differences from the mean is 54. The average deviation is 4.5. This value being higher than 1.83, shows that distribution B is more spread out than distribution A, which makes sense just looking at the dotplots of the data.</p>
</div>
<div id="standard-deviation" class="section level3" number="6.4.4">
<h3><span class="header-section-number">6.4.4</span> Standard Deviation</h3>
<p>An alternative, and much more common method of calculating the ‘deviation’ from the mean of the average datapoint is the standard deviation. This is very similar to the absolute deviation, but the method of making the difference scores positive is different. In average deviation, we just ignore the sign of the difference scores and we make everything positive (this is called taking the absolute value). In standard deviation the method used to make these difference scores positive is to square them.</p>
<p>Let’s look at how this one works for our two distributions. We’ll start with distribution A again.</p>
<p>First step, is again to get the difference scores, by taking each datapoint away from the mean of the distribution:</p>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="descriptives.html#cb594-1" aria-hidden="true" tabindex="-1"></a>A <span class="sc">-</span> <span class="fu">mean</span>(A)</span></code></pre></div>
<pre><code>##  [1] -5 -2 -2 -1 -1  0  0  1  2  2  2  4</code></pre>
<p>Next, we square these difference scores to get positive values:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="descriptives.html#cb596-1" aria-hidden="true" tabindex="-1"></a>(A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 25  4  4  1  1  0  0  1  4  4  4 16</code></pre>
<p>Notice that the datapoints that are furthest from the mean get proportionally larger than values that are close to the mean. Squaring has this effect.</p>
<p>We need to sum these “squared differences” to get a measure of how much deviation there is in total - this figure can also be called the <strong>Sum of Squares</strong> or <strong>Sum of Squared Differences</strong>:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="descriptives.html#cb598-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 64</code></pre>
<p>The total of the squared differences is 64. The notation for this is:</p>
<p><span class="math inline">\(\Sigma(x-\mu)^2\)</span></p>
<p>To get a sense of the average squared difference, we then divide the total of the squared differences by our <span class="math inline">\(N\)</span>:</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="descriptives.html#cb600-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 5.333333</code></pre>
<p>The average squared difference is 5.33. The notation for this is <span class="math inline">\(\frac{\Sigma(x-\mu)^2}{N}\)</span>.</p>
<p>This is a useful measure of deviation, but unfortunately it is still in the units of “squared differences”. To get it back to the original units of the distribution we just square root it and we call this the “standard deviation”:</p>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="descriptives.html#cb602-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">5.333333</span>) </span></code></pre></div>
<pre><code>## [1] 2.309401</code></pre>
<p>The standard deviation <span class="math inline">\(\sigma=2.309\)</span>. The notation for this is:</p>
<p><span class="math inline">\(\sigma = \sqrt{\frac{\Sigma(x-\mu)^2}{N}}\)</span></p>
<p>We are using <span class="math inline">\(\sigma\)</span> to represent the <strong>population standard deviation</strong>.</p>
<p>We can do the same thing for our population B. Let’s calculate the difference scores, then square them, then add them up, then divide by <span class="math inline">\(N\)</span>, and finally square root:</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="descriptives.html#cb604-1" aria-hidden="true" tabindex="-1"></a><span class="co"># difference scores</span></span>
<span id="cb604-2"><a href="descriptives.html#cb604-2" aria-hidden="true" tabindex="-1"></a>B <span class="sc">-</span> <span class="fu">mean</span>(B)</span></code></pre></div>
<pre><code>##  [1] -8 -7 -6 -4 -2  0  1  2  3  5  7  9</code></pre>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="descriptives.html#cb606-1" aria-hidden="true" tabindex="-1"></a><span class="co"># squared difference scores</span></span>
<span id="cb606-2"><a href="descriptives.html#cb606-2" aria-hidden="true" tabindex="-1"></a>(B <span class="sc">-</span> <span class="fu">mean</span>(B))<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 64 49 36 16  4  0  1  4  9 25 49 81</code></pre>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="descriptives.html#cb608-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sum of squared differences</span></span>
<span id="cb608-2"><a href="descriptives.html#cb608-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((B <span class="sc">-</span> <span class="fu">mean</span>(B))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 338</code></pre>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="descriptives.html#cb610-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average squared difference</span></span>
<span id="cb610-2"><a href="descriptives.html#cb610-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((B <span class="sc">-</span> <span class="fu">mean</span>(B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">12</span></span></code></pre></div>
<pre><code>## [1] 28.16667</code></pre>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="descriptives.html#cb612-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard Deviation</span></span>
<span id="cb612-2"><a href="descriptives.html#cb612-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>((B <span class="sc">-</span> <span class="fu">mean</span>(B))<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="dv">12</span>)</span></code></pre></div>
<pre><code>## [1] 5.307228</code></pre>
<p>The population standard deviation <span class="math inline">\(\sigma\)</span> for population B is 5.31. Again, as this value is higher than 2.31 this suggests that population B is more spread out than population A, because its datapoints are on average further from the mean.</p>
</div>
<div id="variance" class="section level3" number="6.4.5">
<h3><span class="header-section-number">6.4.5</span> Variance</h3>
<p>Variance is related to standard deviation. In fact, it is just standard deviation squared. It can be calculated by the formula:</p>
<p><span class="math inline">\(\sigma^2 = \sigma^2\)</span></p>
<p>which is a bit ridiculous. Variance is denoted by <span class="math inline">\(\sigma^2\)</span> and is calculated by squaring the standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p>It’s actually the value you get before you do the square root step when calculating standard deviation. Therefore, we can actually say:</p>
<p><span class="math inline">\(\sigma^2 = \frac{\Sigma(x-\mu)^2}{N}\)</span></p>
</div>
<div id="average-versus-standard-deviation" class="section level3" number="6.4.6">
<h3><span class="header-section-number">6.4.6</span> Average versus Standard Deviation</h3>
<p>So why do we have two methods for calculating the deviation from the mean. We have the “average deviation” and the “standard deviation”. One thing you should notice is that the standard deviation is larger than the average deviation. Distribution A had an average deviation of 4.5 and a standard deviation of 5.3. Distribution B had an average deviation of 1.83 and a standard deviation of 2.3. The reason for this is that squaring difference scores leads to larger values than just taking absolute values. So why do we do the squaring thing? The main reason is that it emphasizes datapoints that are further away from the mean, and this can be an important aspect of spread that we need to take account for. Because of that, it is favored to use the ‘standard deviation’ above the ‘average deviation’.</p>
</div>
<div id="sample-standard-deviation" class="section level3" number="6.4.7">
<h3><span class="header-section-number">6.4.7</span> Sample Standard Deviation</h3>
<p>Something that is often confusing in introductory statistics is that there are two different formulas for calculating the standard deviation. The one we have already introduced above is called the <strong>population standard deviation</strong> and its formula is:</p>
<p><span class="math inline">\(\sigma = \sqrt{\frac{\Sigma(x-\mu)^2}{N}}\)</span></p>
<p>But, we use a different formula when we are calculating the standard deviation for a <em>sample</em>. This is called the <strong>sample standard deviation</strong>:</p>
<p><span class="math inline">\(s = \sqrt{\frac{\Sigma(x-\mu)^2}{n-1}}\)</span></p>
<p>Notice two things. First, we use the notation <span class="math inline">\(s\)</span> to indicate a sample standard deviation. Second, instead of dividing by <span class="math inline">\(N\)</span> in the formula, we divide by <span class="math inline">\(n-1\)</span>.</p>
<p>So, for our example data distribution of <code>A</code>, this is how we would calculate <span class="math inline">\(s\)</span>:</p>
<p>First, we get the difference scores, by subtracting the mean of the distribution from each score:</p>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="descriptives.html#cb614-1" aria-hidden="true" tabindex="-1"></a><span class="co">#difference scores</span></span>
<span id="cb614-2"><a href="descriptives.html#cb614-2" aria-hidden="true" tabindex="-1"></a>A <span class="sc">-</span> <span class="fu">mean</span>(A)</span></code></pre></div>
<pre><code>##  [1] -5 -2 -2 -1 -1  0  0  1  2  2  2  4</code></pre>
<p>Second, we square these difference scores to make them positive and to emphasize larger difference scores:</p>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="descriptives.html#cb616-1" aria-hidden="true" tabindex="-1"></a><span class="co">#square the difference scores</span></span>
<span id="cb616-2"><a href="descriptives.html#cb616-2" aria-hidden="true" tabindex="-1"></a>(A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 25  4  4  1  1  0  0  1  4  4  4 16</code></pre>
<p>Third, we sum up all the squared difference scores:</p>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="descriptives.html#cb618-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sum the squared difference scores</span></span>
<span id="cb618-2"><a href="descriptives.html#cb618-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 64</code></pre>
<p>Fourth, we divide this sum by <span class="math inline">\(n-1\)</span>, which technically gives us the variance:</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="descriptives.html#cb620-1" aria-hidden="true" tabindex="-1"></a><span class="co">#divide by n-1 to get the variance</span></span>
<span id="cb620-2"><a href="descriptives.html#cb620-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the &#39;n&#39; is 12 here</span></span>
<span id="cb620-3"><a href="descriptives.html#cb620-3" aria-hidden="true" tabindex="-1"></a>(<span class="fu">sum</span>((A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span>(<span class="dv">12-1</span>)</span></code></pre></div>
<pre><code>## [1] 5.818182</code></pre>
<p>Finally, we square root this value to get the sample standard deviation - a measure of the typical deviation of each datapoint from the mean:</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="descriptives.html#cb622-1" aria-hidden="true" tabindex="-1"></a><span class="co">#square root to get the SD</span></span>
<span id="cb622-2"><a href="descriptives.html#cb622-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>((<span class="fu">sum</span>((A <span class="sc">-</span> <span class="fu">mean</span>(A))<span class="sc">^</span><span class="dv">2</span>))<span class="sc">/</span>(<span class="dv">12-1</span>))</span></code></pre></div>
<pre><code>## [1] 2.412091</code></pre>
<p>Here we have manually calculated the sample standard deviation <span class="math inline">\(s=2.412\)</span>. Earlier in this chapter we calculated the population standard deviation of this same distribution to be <span class="math inline">\(\sigma=2.309\)</span>. Notice that the sample standard deviation <span class="math inline">\(s\)</span> is larger than the population standard deviation <span class="math inline">\(\sigma\)</span>. This is because <span class="math inline">\(n-1\)</span> will always be smaller than <span class="math inline">\(N\)</span>, inflating the final result.</p>
<p>So far, we haven’t shown you the shortcut for calculating the standard deviation in R. It’s actually just the function <code>sd()</code>:</p>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="descriptives.html#cb624-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(A)</span></code></pre></div>
<pre><code>## [1] 2.412091</code></pre>
<p>Hopefully you notice that the output of <code>sd()</code> is the sample standard deviation and not the population standard deviation.</p>
<p>There is actually no built in function for calculating the population standard deviation <span class="math inline">\(\sigma\)</span> in R. The below code is a custom function to calculate it that we made. It’s called <code>pop.sd()</code>.</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="descriptives.html#cb626-1" aria-hidden="true" tabindex="-1"></a><span class="co"># this is a custom function to calculate</span></span>
<span id="cb626-2"><a href="descriptives.html#cb626-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the population standard deviation </span></span>
<span id="cb626-3"><a href="descriptives.html#cb626-3" aria-hidden="true" tabindex="-1"></a> pop.sd <span class="ot">&lt;-</span> <span class="cf">function</span>(s) { </span>
<span id="cb626-4"><a href="descriptives.html#cb626-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">sqrt</span>(<span class="fu">sum</span>((s <span class="sc">-</span> <span class="fu">mean</span>(s))<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">length</span>(s)) </span>
<span id="cb626-5"><a href="descriptives.html#cb626-5" aria-hidden="true" tabindex="-1"></a> } </span></code></pre></div>
<p>When we look at the population standard deviation of A we can see that it matches what we worked out by hand earlier:</p>
<div class="sourceCode" id="cb627"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb627-1"><a href="descriptives.html#cb627-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pop.sd</span>(A) </span></code></pre></div>
<pre><code>## [1] 2.309401</code></pre>
<p>Let’s look at distribution B for its sample and population standard deviations:</p>
<div class="sourceCode" id="cb629"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb629-1"><a href="descriptives.html#cb629-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(B)</span></code></pre></div>
<pre><code>## [1] 5.543219</code></pre>
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb631-1"><a href="descriptives.html#cb631-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pop.sd</span>(B)</span></code></pre></div>
<pre><code>## [1] 5.307228</code></pre>
<p>Again you can see that <span class="math inline">\(s=5.543\)</span> is greater than <span class="math inline">\(\sigma=5.307\)</span>. Both these values are higher than the standard deviations for distribution A, indicating that distribution B is more spread out and less clumped than distribution A.</p>
</div>
<div id="sample-versus-population-standard-deviation" class="section level3" number="6.4.8">
<h3><span class="header-section-number">6.4.8</span> Sample versus Population Standard Deviation</h3>
<p>So why are there two formulas, and why do we divide by <span class="math inline">\(n-1\)</span> in the sample standard deviation? The short answer is that whenever we determine the standard deviation for a sample, our goal is technically not to ‘calculate’ the standard deviation just for that sample. The bigger goal is that we are trying to <strong>estimate</strong> the population standard deviation <span class="math inline">\(\sigma\)</span>. However, when we use the population SD formula on samples, we consistently underestimate the real population standard deviation. Why is this? Basically it’s for two reasons. First, within any one sample we typically have much less variation than we do in our population, so we tend to underestimate the true variation. Secondly, when we have our sample we use our sample mean <span class="math inline">\(\overline{x}\)</span> as an estimate of the population mean <span class="math inline">\(\mu\)</span>. Because <span class="math inline">\(\overline{x}\)</span> will be usually slightly different from <span class="math inline">\(\mu\)</span> we will be usually underestimating the true deviation from the mean in the population.</p>
<p>The bottom line is this: using the population SD formula for a sample generally gives an <strong>underestimate</strong> of the true population standard deviation <span class="math inline">\(\sigma\)</span>. The solution is to use a fudge-factor of dividing by <span class="math inline">\(n-1\)</span> which bumps up the standard deviation. This is what we do in the sample standard deviation formula.</p>
<p>In the sections below, we are going to visually demonstrate this. Hopefully this helps to show you that dividing by <span class="math inline">\(n-1\)</span> works. Don’t worry too much about any code here, the aim isn’t for you to learn how to run simulations such as these, but we want you to be able to visually see what’s going on.</p>
<div id="comparing-population-and-sample-means" class="section level4" number="6.4.8.1">
<h4><span class="header-section-number">6.4.8.1</span> Comparing population and sample means</h4>
<p>Before we get to why we need a separate formula for the sample standard deviation, let’s show you why we don’t need a separate formula for the sample mean compared to the population mean. Both of these formulas are essentially the same:</p>
<p>Sample mean:
<span class="math inline">\(\Large\overline{x} = \frac{\Sigma{x}}{n}\)</span></p>
<p><br></p>
<p>Population mean:<br />
<span class="math inline">\(\Large \mu = \frac{\Sigma{x}}{N}\)</span></p>
<p>Let’s assume the following data distribution is our population, we’ll call it <code>pop</code>. The following code creates a population of 10000 numbers drawn from a random normal distribution (see section <a href="distributions.html#normal-distribution">7.0.3</a>) with a population mean of 8 and population standard deviation of 2. Because we’re randomly drawing numbers to make our population, the final population won’t have a mean and standard deviation that are precisely 8 and 2, but we can calculate what they turn out to be:</p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb633-1"><a href="descriptives.html#cb633-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>) <span class="co"># just so we all get the same results</span></span>
<span id="cb633-2"><a href="descriptives.html#cb633-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb633-3"><a href="descriptives.html#cb633-3" aria-hidden="true" tabindex="-1"></a>pop <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">8</span>, <span class="at">sd =</span> <span class="dv">2</span>) <span class="co">#100 random numbers with mean of 8, popSD of 2.</span></span></code></pre></div>
<p>We now have our population of size <span class="math inline">\(N=10000\)</span>. We can precisely calculate the population mean <span class="math inline">\(\mu\)</span> and population standard deviation <span class="math inline">\(\sigma\)</span> of our 10000 numbers using <code>mean()</code> and <code>pop.sd()</code>:</p>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="descriptives.html#cb634-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pop)      </span></code></pre></div>
<pre><code>## [1] 7.986926</code></pre>
<div class="sourceCode" id="cb636"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb636-1"><a href="descriptives.html#cb636-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pop.sd</span>(pop) </span></code></pre></div>
<pre><code>## [1] 2.024612</code></pre>
<p>So our population has a mean <span class="math inline">\(\mu=7.99\)</span> and population standard deviation <span class="math inline">\(\sigma=2.02\)</span>.</p>
<p>Let’s now start taking samples. We’ll just choose samples of size <span class="math inline">\(n=10\)</span>. We can get samples using <code>sample()</code> in R. Let’s look at the sample mean of each sample:</p>
<div class="sourceCode" id="cb638"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb638-1"><a href="descriptives.html#cb638-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first sample</span></span>
<span id="cb638-2"><a href="descriptives.html#cb638-2" aria-hidden="true" tabindex="-1"></a>samp1 <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb638-3"><a href="descriptives.html#cb638-3" aria-hidden="true" tabindex="-1"></a>samp1</span></code></pre></div>
<pre><code>##  [1]  3.722781  8.785220  6.045566 11.705993  7.297500  7.399121 11.976971
##  [8]  8.401657  6.306361  7.152555</code></pre>
<div class="sourceCode" id="cb640"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb640-1"><a href="descriptives.html#cb640-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(samp1)</span></code></pre></div>
<pre><code>## [1] 7.879373</code></pre>
<p>Here our sample mean <span class="math inline">\(\overline{x}=8.62\)</span> which is close-ish, but a fair bit above <span class="math inline">\(\mu=7.99\)</span>.</p>
<p>Let’s do it again:</p>
<div class="sourceCode" id="cb642"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb642-1"><a href="descriptives.html#cb642-1" aria-hidden="true" tabindex="-1"></a><span class="co">#second sample</span></span>
<span id="cb642-2"><a href="descriptives.html#cb642-2" aria-hidden="true" tabindex="-1"></a>samp2 <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb642-3"><a href="descriptives.html#cb642-3" aria-hidden="true" tabindex="-1"></a>samp2</span></code></pre></div>
<pre><code>##  [1]  6.142884  7.614448  9.575279  9.072075  4.108463 10.599279  8.224608
##  [8]  6.735289  7.004465  7.791237</code></pre>
<div class="sourceCode" id="cb644"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb644-1"><a href="descriptives.html#cb644-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(samp2)</span></code></pre></div>
<pre><code>## [1] 7.686803</code></pre>
<p>Again our value of <span class="math inline">\(\overline{x}=8.10\)</span> is above <span class="math inline">\(\mu=7.99\)</span>, but this time much closer.</p>
<p>Let’s do a third sample:</p>
<div class="sourceCode" id="cb646"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb646-1"><a href="descriptives.html#cb646-1" aria-hidden="true" tabindex="-1"></a><span class="co">#third sample</span></span>
<span id="cb646-2"><a href="descriptives.html#cb646-2" aria-hidden="true" tabindex="-1"></a>samp3 <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb646-3"><a href="descriptives.html#cb646-3" aria-hidden="true" tabindex="-1"></a>samp3</span></code></pre></div>
<pre><code>##  [1]  8.352818 12.802444 10.304643  6.061141  8.633719  8.028558  7.350359
##  [8]  5.904344  6.875784 11.512439</code></pre>
<div class="sourceCode" id="cb648"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb648-1"><a href="descriptives.html#cb648-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(samp3)</span></code></pre></div>
<pre><code>## [1] 8.582625</code></pre>
<p>This time our value of <span class="math inline">\(\overline{x}=7.86\)</span> is a bit below <span class="math inline">\(\mu=7.99\)</span>.</p>
<p>What if we did this thousands and thousands of times? Would our sample mean be more often lower or higher than the population mean <span class="math inline">\(\mu=7.99\)</span>?</p>
<p>This is what the code below is doing - it’s effectively grabbing a sample of size 10 and then calculating the sample mean, but it’s doing this 20,000 times. It’s storing all the sample means in an object called <code>results.means</code>.</p>
<p>Note: you don’t need to know how this code works! though do reach out if you are interested.</p>
<div class="sourceCode" id="cb650"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb650-1"><a href="descriptives.html#cb650-1" aria-hidden="true" tabindex="-1"></a>results.means<span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&#39;list&#39;</span>,<span class="dv">20000</span>)</span>
<span id="cb650-2"><a href="descriptives.html#cb650-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb650-3"><a href="descriptives.html#cb650-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20000</span>){</span>
<span id="cb650-4"><a href="descriptives.html#cb650-4" aria-hidden="true" tabindex="-1"></a>  samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb650-5"><a href="descriptives.html#cb650-5" aria-hidden="true" tabindex="-1"></a>  results.means[[i]] <span class="ot">&lt;-</span> <span class="fu">mean</span>(samp)</span>
<span id="cb650-6"><a href="descriptives.html#cb650-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Let’s look at 10 of these sample means we just collected:</p>
<div class="sourceCode" id="cb651"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb651-1"><a href="descriptives.html#cb651-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unlist</span>(results.means)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>##  [1] 7.457507 7.804544 8.099342 7.886644 7.642569 8.228794 8.581173 7.417380
##  [9] 7.098994 7.458659</code></pre>
<p>Some are above and some are below <span class="math inline">\(\mu=7.99\)</span>.</p>
<p>Let’s calculate the mean of all the 20,000 sample means:</p>
<div class="sourceCode" id="cb653"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb653-1"><a href="descriptives.html#cb653-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">unlist</span>(results.means))</span></code></pre></div>
<pre><code>## [1] 7.990952</code></pre>
<p>It turns out that the average sample mean that we collect using the formula <span class="math inline">\(\Large \overline{x} = \frac{\Sigma{x}}{n}\)</span> is 7.99 which is the same as the population mean <span class="math inline">\(\mu\)</span>. What this means is that this formula is perfectly fine to use to <strong>estimate</strong> the population mean. It is what we call an <strong>unbiased estimator</strong>. Over the long run, it gives us a very good estimate of the population mean <span class="math inline">\(\mu\)</span>. Here is a histogram of our sample means from our 20,000 samples:</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-327-1.png" width="672" /></p>
<p>The vertical solid black line represents <span class="math inline">\(\mu=7.99\)</span>. This histogram is centered on this value, showing that our sample mean formula is unbiased in estimating the population mean - overall, it isn’t under- or over-estimating the population mean.</p>
<p>As a side note - what we just did in the exercise above was to calculate a <em>sampling distribution of sample means</em> - something we’ll discuss much more in section <a href="distributions.html#what-is-a-sampling-distribution">7.2</a>.</p>
<p><br></p>
</div>
<div id="sample-standard-deviation-as-an-unbiased-estimator" class="section level4" number="6.4.8.2">
<h4><span class="header-section-number">6.4.8.2</span> Sample standard deviation as an unbiased estimator</h4>
<p>Let’s do something similar with our two formulas for calculating standard deviation. We’ll take samples of size <span class="math inline">\(n=10\)</span> and use the sample standard deviation <span class="math inline">\(s\)</span> and the population standard deviation <span class="math inline">\(\sigma\)</span> formulas to estimate the true <span class="math inline">\(\sigma=2.02\)</span>.</p>
<div class="sourceCode" id="cb655"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb655-1"><a href="descriptives.html#cb655-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first sample</span></span>
<span id="cb655-2"><a href="descriptives.html#cb655-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(samp1)</span></code></pre></div>
<pre><code>## [1] 2.510835</code></pre>
<div class="sourceCode" id="cb657"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb657-1"><a href="descriptives.html#cb657-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pop.sd</span>(samp1)</span></code></pre></div>
<pre><code>## [1] 2.381987</code></pre>
<p>With the first sample, both estimates are lower than <span class="math inline">\(\sigma=2.02\)</span>, although the sample standard deviation is a bit closer to <span class="math inline">\(\sigma=2.02\)</span>.</p>
<div class="sourceCode" id="cb659"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb659-1"><a href="descriptives.html#cb659-1" aria-hidden="true" tabindex="-1"></a><span class="co">#second sample</span></span>
<span id="cb659-2"><a href="descriptives.html#cb659-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(samp2)</span></code></pre></div>
<pre><code>## [1] 1.850897</code></pre>
<div class="sourceCode" id="cb661"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb661-1"><a href="descriptives.html#cb661-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pop.sd</span>(samp2)</span></code></pre></div>
<pre><code>## [1] 1.755915</code></pre>
<p>With the second sample of 10, both estimates are even lower than <span class="math inline">\(\sigma=2.02\)</span>. Again, the sample standard deviation formula produces a result that is closer to 2.02 than does the population deviation formula.</p>
<p>What if we did this for 20,000 samples of size 10? We’ll save the estimates using the sample SD formula in the object <code>results.samp.sd</code> and the estimates using the population SD formula in <code>results.pop.sd</code>. Again, don’t worry about the code here - just focus on the output:</p>
<div class="sourceCode" id="cb663"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb663-1"><a href="descriptives.html#cb663-1" aria-hidden="true" tabindex="-1"></a>results.samp.sd<span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&#39;list&#39;</span>,<span class="dv">20000</span>)</span>
<span id="cb663-2"><a href="descriptives.html#cb663-2" aria-hidden="true" tabindex="-1"></a>results.pop.sd<span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&#39;list&#39;</span>,<span class="dv">20000</span>)</span>
<span id="cb663-3"><a href="descriptives.html#cb663-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb663-4"><a href="descriptives.html#cb663-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20000</span>){</span>
<span id="cb663-5"><a href="descriptives.html#cb663-5" aria-hidden="true" tabindex="-1"></a>  samp <span class="ot">&lt;-</span> <span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> T)</span>
<span id="cb663-6"><a href="descriptives.html#cb663-6" aria-hidden="true" tabindex="-1"></a>  results.samp.sd[[i]] <span class="ot">&lt;-</span> <span class="fu">sd</span>(samp)</span>
<span id="cb663-7"><a href="descriptives.html#cb663-7" aria-hidden="true" tabindex="-1"></a>  results.pop.sd[[i]] <span class="ot">&lt;-</span> <span class="fu">pop.sd</span>(samp)</span>
<span id="cb663-8"><a href="descriptives.html#cb663-8" aria-hidden="true" tabindex="-1"></a>  }</span></code></pre></div>
<p>We can work out the average estimate of the standard deviation across all 20,000 samples:</p>
<div class="sourceCode" id="cb664"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb664-1"><a href="descriptives.html#cb664-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">unlist</span>(results.samp.sd))</span></code></pre></div>
<pre><code>## [1] 1.967842</code></pre>
<div class="sourceCode" id="cb666"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb666-1"><a href="descriptives.html#cb666-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">unlist</span>(results.pop.sd))</span></code></pre></div>
<pre><code>## [1] 1.866859</code></pre>
<p>So, over 20,000 samples both formulas actually overall underestimate the true population standard deviation of <span class="math inline">\(\sigma=2.02\)</span>, however, the sample standard deviation formula is closer with it’s average being 1.97 compared to the population standard deviation’s formula being at 1.87.</p>
<p>We can graph this like this:</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-332-1.png" width="672" /></p>
<p>This visualization shows us a few things. First, over all 20,000 samples, some of our estimates of the true standard deviation <span class="math inline">\(\sigma\)</span> are higher and some are lower regardless of which formula we use. However, when we use the population formula (dividing by <span class="math inline">\(N\)</span>), we have far more samples with estimates of the standard deviation <span class="math inline">\(\sigma\)</span> which are too low. The distribution is clearly not symmetrical. If we consider the right histogram, when we use the sample SD formula (dividing by <span class="math inline">\(n-1\)</span>), we correct this by and large. This histogram is closer to symmetrical, and we are not underestimating the true population standard deviation nearly as much. In this way, we called the sample standard deviation <span class="math inline">\(s\)</span> an <strong>unbiased estimator</strong>.</p>
<p>If we were to take larger sample sizes, then our estimates of the population standard deviation <span class="math inline">\(\sigma\)</span>, would get better and better when using the sample standard deviation formula.</p>
<p><br><br></p>
</div>
</div>
</div>
<div id="descriptive-statistics-in-r" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> Descriptive Statistics in R</h2>
<p>The above sections interweaved some theory with how to get descriptive information using R. In this section we’ll summarize how to get descriptive summaries from real data in R.</p>
<p>The dataset that we’ll use is a year’s worth of temperature data from Austin, TX.</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="descriptives.html#cb668-1" aria-hidden="true" tabindex="-1"></a>atx <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/austin_weather.csv&quot;</span>)</span>
<span id="cb668-2"><a href="descriptives.html#cb668-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(atx) <span class="co"># first 6 rows</span></span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   month   day  year  temp
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     1  2019  43.3
## 2     1     2  2019  39.4
## 3     1     3  2019  41.2
## 4     1     4  2019  44.1
## 5     1     5  2019  48.6
## 6     1     6  2019  48.8</code></pre>
<p>The <code>temp</code> column shows the average temperature for that day of the year in 2019. Here is a histogram showing the distribution. It is often hot in Texas.</p>
<div class="sourceCode" id="cb670"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb670-1"><a href="descriptives.html#cb670-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(atx, <span class="fu">aes</span>(<span class="at">x=</span> temp)) <span class="sc">+</span> </span>
<span id="cb670-2"><a href="descriptives.html#cb670-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>, <span class="at">fill=</span><span class="st">&quot;lightseagreen&quot;</span>, <span class="at">binwidth =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb670-3"><a href="descriptives.html#cb670-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb670-4"><a href="descriptives.html#cb670-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Average temperature&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-334-1.png" width="672" /></p>
<p><strong>Basic Descriptives</strong></p>
<p>Here is a list of some the basic descriptive commands such as calculating the <span class="math inline">\(n\)</span>, the minimum, maximum and range. We apply each function to the whole column of data <code>atx$temp</code>, i.e. all the numbers of the distribution:</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="descriptives.html#cb671-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(atx<span class="sc">$</span>temp) <span class="co"># length this tells you the &#39;n&#39;</span></span></code></pre></div>
<pre><code>## [1] 365</code></pre>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb673-1"><a href="descriptives.html#cb673-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(atx<span class="sc">$</span>temp) <span class="co"># range </span></span></code></pre></div>
<pre><code>## [1] 34.5 89.2</code></pre>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb675-1"><a href="descriptives.html#cb675-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(atx<span class="sc">$</span>temp) <span class="co"># minimum</span></span></code></pre></div>
<pre><code>## [1] 34.5</code></pre>
<div class="sourceCode" id="cb677"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb677-1"><a href="descriptives.html#cb677-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(atx<span class="sc">$</span>temp) <span class="co"># maximum</span></span></code></pre></div>
<pre><code>## [1] 89.2</code></pre>
<p><strong>Mean, Median, and Mode</strong></p>
<p>These mean and median are straightforward in R:</p>
<div class="sourceCode" id="cb679"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb679-1"><a href="descriptives.html#cb679-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(atx<span class="sc">$</span>temp) <span class="co"># mean</span></span></code></pre></div>
<pre><code>## [1] 68.78767</code></pre>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="descriptives.html#cb681-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(atx<span class="sc">$</span>temp) <span class="co"># median</span></span></code></pre></div>
<pre><code>## [1] 70.8</code></pre>
<p>For some descriptives, like mode, there is not a function already built into R. One option is to use <code>table()</code> to get frequencies - but this isn’t useful when you have relatively large datasets. The output is too large. Another option is to use <code>tidyverse</code> methods. Here, we use <code>group_by()</code> to get each temperature, then we use <code>count()</code> to count how many of each temperature we have, and then <code>arrange()</code> to determine which is most frequent:</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="descriptives.html#cb683-1" aria-hidden="true" tabindex="-1"></a>atx <span class="sc">%&gt;%</span></span>
<span id="cb683-2"><a href="descriptives.html#cb683-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(temp) <span class="sc">%&gt;%</span></span>
<span id="cb683-3"><a href="descriptives.html#cb683-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">%&gt;%</span></span>
<span id="cb683-4"><a href="descriptives.html#cb683-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>n)</span></code></pre></div>
<pre><code>## # A tibble: 248 x 2
## # Groups:   temp [248]
##     temp     n
##    &lt;dbl&gt; &lt;int&gt;
##  1  84.8     5
##  2  51.6     4
##  3  75.5     4
##  4  83.7     4
##  5  84.2     4
##  6  84.3     4
##  7  84.9     4
##  8  86.1     4
##  9  42.3     3
## 10  52       3
## # ... with 238 more rows</code></pre>
<p>This shows us that the modal value is 84.8F. In reality however, the mode is never something that you will calculate outside of an introductory stats class.</p>
<p><strong>Variation</strong></p>
<p>The default standard variation measure in R is the sample standard deviation <code>sd()</code>, and is the one you should pretty much always use:</p>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="descriptives.html#cb685-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(atx<span class="sc">$</span>temp) <span class="co">#  sample standard deviation</span></span></code></pre></div>
<pre><code>## [1] 14.90662</code></pre>
<p>Variance can also be calculated using <code>var()</code> - remember this is the standard deviation squared. When you calculate this using the sample standard deviation <span class="math inline">\(s\)</span> the formula notation for the variance is <span class="math inline">\(s^2\)</span>:</p>
<div class="sourceCode" id="cb687"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb687-1"><a href="descriptives.html#cb687-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(atx<span class="sc">$</span>temp) <span class="co"># variance </span></span></code></pre></div>
<pre><code>## [1] 222.2072</code></pre>
<p>The lower quartile, upper quartile and inter-quartile range can be calculated like this:</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="descriptives.html#cb689-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(atx<span class="sc">$</span>temp, .<span class="dv">25</span>)  <span class="co"># this is the lower quartile</span></span></code></pre></div>
<pre><code>##  25% 
## 56.5</code></pre>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="descriptives.html#cb691-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(atx<span class="sc">$</span>temp, .<span class="dv">75</span>)  <span class="co"># this is the upper quartile</span></span></code></pre></div>
<pre><code>##  75% 
## 83.3</code></pre>
<div class="sourceCode" id="cb693"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb693-1"><a href="descriptives.html#cb693-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(atx<span class="sc">$</span>temp)   <span class="co"># this is the inter-quartile range.</span></span></code></pre></div>
<pre><code>## [1] 26.8</code></pre>
<p>Remember there are several ways of calculating the quartiles (see above).</p>
<div id="dealing-with-missing-data" class="section level3" number="6.5.1">
<h3><span class="header-section-number">6.5.1</span> Dealing with Missing Data</h3>
<p>Often in datasets we have missing data. In R, missing data in our dataframes or vectors is represented by <code>NA</code> or sometimes <code>NaN</code>. A slightly annoying feature of many of the descriptive summary functions is that they do not work if there is missing data.</p>
<p>Here’s an illustration. We’ve created a vector of data called <code>q</code> that has some numbers but also a ‘missing’ piece of data:</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb695-1"><a href="descriptives.html#cb695-1" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">8</span>, <span class="dv">3</span>, <span class="cn">NA</span>, <span class="dv">7</span>, <span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb695-2"><a href="descriptives.html#cb695-2" aria-hidden="true" tabindex="-1"></a>q</span></code></pre></div>
<pre><code>## [1]  5 10  8  3 NA  7  1  2</code></pre>
<p>If we try and calculate some descriptives, R will not like it:</p>
<div class="sourceCode" id="cb697"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb697-1"><a href="descriptives.html#cb697-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(q)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb699"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb699-1"><a href="descriptives.html#cb699-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(q)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb701-1"><a href="descriptives.html#cb701-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(q)</span></code></pre></div>
<pre><code>## [1] NA NA</code></pre>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb703-1"><a href="descriptives.html#cb703-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(q)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>What we have to do in these situations is to override the missing data. We need to tell it that we really do want to get these values and it should remove the missing data before doing that. We do that by adding the argument <code>na.rm=T</code> to the end of each function:</p>
<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb705-1"><a href="descriptives.html#cb705-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(q, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## [1] 5.142857</code></pre>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb707-1"><a href="descriptives.html#cb707-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(q, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## [1] 3.338092</code></pre>
<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb709-1"><a href="descriptives.html#cb709-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(q, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## [1]  1 10</code></pre>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb711-1"><a href="descriptives.html#cb711-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(q, <span class="at">na.rm=</span>T)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Now R is happy to do what we want.</p>
<p>The only ‘gotcha’ that you need to watch out for is <code>length()</code> which we sometimes use to calculate the <span class="math inline">\(n\)</span> of a vector. If we do this for <code>q</code>, we’ll get 8, which includes our missing value:</p>
<div class="sourceCode" id="cb713"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb713-1"><a href="descriptives.html#cb713-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(q)</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p>This is a way of getting around that - it looks odd, so we’ve just put it here for reference. It’s not necessary for you to remember this. It’s essentially asking what is the length of <code>q</code> when you don’t include the <code>NA</code>:</p>
<div class="sourceCode" id="cb715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb715-1"><a href="descriptives.html#cb715-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(q[<span class="sc">!</span><span class="fu">is.na</span>(q)])</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
</div>
</div>
<div id="descriptives-for-datasets" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Descriptives for Datasets</h2>
<p>Often in studies, we are interested in many different outcome variables at once. We are also interested in how groups differ in various descriptive statistics. The following code will show you how to get descriptive statistics for several columns. In the next section we’ll discuss getting descriptives for different groups from data.</p>
<p>First read in these data that are looking at various sales of different video games.</p>
<div class="sourceCode" id="cb717"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb717-1"><a href="descriptives.html#cb717-1" aria-hidden="true" tabindex="-1"></a>vg <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/videogames.csv&quot;</span>)</span>
<span id="cb717-2"><a href="descriptives.html#cb717-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb717-3"><a href="descriptives.html#cb717-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vg)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 12
##   name  platform  year genre publisher NA_sales EU_sales JP_sales global_sales
##   &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;
## 1 Wii ~ Wii       2006 Spor~ Nintendo     41.4     29.0      3.77         82.5
## 2 Mari~ Wii       2008 Raci~ Nintendo     15.7     12.8      3.79         35.6
## 3 Wii ~ Wii       2009 Spor~ Nintendo     15.6     11.0      3.28         32.8
## 4 Wii ~ Wii       2007 Spor~ Nintendo      8.92     8.03     3.6          22.7
## 5 Wii ~ Wii       2009 Spor~ Nintendo      9.01     8.49     2.53         21.8
## 6 Gran~ PS3       2013 Acti~ Take-Two~     7.02     9.14     0.98         21.1
## # ... with 3 more variables: critic &lt;dbl&gt;, user &lt;dbl&gt;, rating &lt;chr&gt;</code></pre>
<p>One way to get quick summary information is to use the R function <code>summary()</code> like this:</p>
<div class="sourceCode" id="cb719"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb719-1"><a href="descriptives.html#cb719-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vg)</span></code></pre></div>
<pre><code>##      name             platform              year         genre          
##  Length:2502        Length:2502        Min.   :1992   Length:2502       
##  Class :character   Class :character   1st Qu.:2005   Class :character  
##  Mode  :character   Mode  :character   Median :2008   Mode  :character  
##                                        Mean   :2008                     
##                                        3rd Qu.:2011                     
##                                        Max.   :2016                     
##   publisher            NA_sales          EU_sales          JP_sales      
##  Length:2502        Min.   : 0.0000   Min.   : 0.0000   Min.   :0.00000  
##  Class :character   1st Qu.: 0.0700   1st Qu.: 0.0200   1st Qu.:0.00000  
##  Mode  :character   Median : 0.1800   Median : 0.1000   Median :0.00000  
##                     Mean   : 0.4852   Mean   : 0.3012   Mean   :0.04023  
##                     3rd Qu.: 0.4675   3rd Qu.: 0.2800   3rd Qu.:0.01000  
##                     Max.   :41.3600   Max.   :28.9600   Max.   :3.79000  
##   global_sales         critic           user          rating         
##  Min.   : 0.0100   Min.   :13.00   Min.   :0.700   Length:2502       
##  1st Qu.: 0.1500   1st Qu.:61.00   1st Qu.:6.200   Class :character  
##  Median : 0.3800   Median :72.00   Median :7.400   Mode  :character  
##  Mean   : 0.9463   Mean   :69.98   Mean   :7.027                     
##  3rd Qu.: 0.9275   3rd Qu.:81.00   3rd Qu.:8.100                     
##  Max.   :82.5400   Max.   :98.00   Max.   :9.300</code></pre>
<p>You’ll notice here that it just gives you some summary information for different columns, even those that have no numerical data in them. It’s also not broken down by groups. However, <code>summary()</code> can be a quick way to get some summary information.</p>
<p>A slightly better function is <code>Describe()</code> in the <code>psych</code> package. Remember to install the <code>psych</code> package before using it. Also, here we are telling it only to provide summaries of the relevant numeric columns (which are the 6th through 11th columns):</p>
<div class="sourceCode" id="cb721"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb721-1"><a href="descriptives.html#cb721-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb721-2"><a href="descriptives.html#cb721-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(vg[<span class="fu">c</span>(<span class="dv">6</span><span class="sc">:</span><span class="dv">11</span>)])</span></code></pre></div>
<pre><code>##              vars    n  mean    sd median trimmed   mad   min   max range
## NA_sales        1 2502  0.49  1.29   0.18    0.27  0.21  0.00 41.36 41.36
## EU_sales        2 2502  0.30  0.90   0.10    0.15  0.13  0.00 28.96 28.96
## JP_sales        3 2502  0.04  0.20   0.00    0.01  0.00  0.00  3.79  3.79
## global_sales    4 2502  0.95  2.56   0.38    0.53  0.42  0.01 82.54 82.53
## critic          5 2502 69.98 14.34  72.00   71.03 14.83 13.00 98.00 85.00
## user            6 2502  7.03  1.44   7.40    7.19  1.33  0.70  9.30  8.60
##               skew kurtosis   se
## NA_sales     15.79   422.23 0.03
## EU_sales     16.63   444.50 0.02
## JP_sales     12.05   191.56 0.00
## global_sales 16.52   441.74 0.05
## critic       -0.67     0.07 0.29
## user         -1.06     1.06 0.03</code></pre>
<p>This function also includes some descriptives that we don’t necessarily need to worry about right now, but it does contain most of the ones we are concerned with.</p>
<div id="descriptives-for-groups" class="section level3" number="6.6.1">
<h3><span class="header-section-number">6.6.1</span> Descriptives for Groups</h3>
<p>There are a few ways of getting descriptives for different groups. In our videogame dataset <code>vg</code>, we have a column called <code>genre</code>. We can use the function <code>table()</code> to get the <span class="math inline">\(n\)</span> for all groups.</p>
<div class="sourceCode" id="cb723"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb723-1"><a href="descriptives.html#cb723-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(vg<span class="sc">$</span>genre)</span></code></pre></div>
<pre><code>## 
##  Action  Racing Shooter  Sports 
##     997     349     583     573</code></pre>
<p>We have four different groups of genres, and we might want to get descriptives for each. We can use the function <code>describeBy()</code> from the <code>psych</code> package to get a very quick and easy, but a bit annoying, look at group summaries. It also ignores missing data which is helpful. We dictate which group to get summaries by using the <code>group = "genre"</code> argument:</p>
<div class="sourceCode" id="cb725"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb725-1"><a href="descriptives.html#cb725-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describeBy</span>(vg[<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">6</span><span class="sc">:</span><span class="dv">11</span>)], <span class="at">group =</span> <span class="st">&quot;genre&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Descriptive statistics by group 
## genre: Action
##              vars   n  mean    sd median trimmed   mad   min   max range
## genre*          1 997  1.00  0.00   1.00    1.00  0.00  1.00  1.00  0.00
## NA_sales        2 997  0.41  0.82   0.17    0.24  0.19  0.00  9.66  9.66
## EU_sales        3 997  0.27  0.58   0.10    0.15  0.13  0.00  9.14  9.14
## JP_sales        4 997  0.05  0.14   0.00    0.01  0.00  0.00  1.13  1.13
## global_sales    5 997  0.83  1.67   0.36    0.50  0.39  0.01 21.12 21.11
## critic          6 997 68.02 14.21  70.00   68.63 14.83 20.00 98.00 78.00
## user            7 997  7.12  1.34   7.40    7.26  1.19  1.70  9.30  7.60
##               skew kurtosis   se
## genre*         NaN      NaN 0.00
## NA_sales      6.19    52.60 0.03
## EU_sales      7.14    77.32 0.02
## JP_sales      4.44    22.38 0.00
## global_sales  6.66    61.52 0.05
## critic       -0.38    -0.31 0.45
## user         -1.04     1.05 0.04
## ---------------------------------------------------------- 
## genre: Racing
##              vars   n  mean    sd median trimmed   mad   min   max range
## genre*          1 349  1.00  0.00   1.00    1.00  0.00  1.00  1.00  0.00
## NA_sales        2 349  0.40  1.03   0.13    0.22  0.18  0.00 15.68 15.68
## EU_sales        3 349  0.31  0.85   0.10    0.17  0.13  0.00 12.80 12.80
## JP_sales        4 349  0.03  0.24   0.00    0.00  0.00  0.00  3.79  3.79
## global_sales    5 349  0.86  2.36   0.30    0.48  0.36  0.01 35.57 35.56
## critic          6 349 69.84 14.01  72.00   71.18 14.83 13.00 95.00 82.00
## user            7 349  6.99  1.50   7.30    7.16  1.48  1.00  9.20  8.20
##               skew kurtosis   se
## genre*         NaN      NaN 0.00
## NA_sales     10.36   140.24 0.06
## EU_sales     10.23   135.03 0.05
## JP_sales     12.65   180.01 0.01
## global_sales 10.34   136.42 0.13
## critic       -0.92     0.87 0.75
## user         -1.05     1.06 0.08
## ---------------------------------------------------------- 
## genre: Shooter
##              vars   n  mean    sd median trimmed   mad   min   max range
## genre*          1 583  1.00  0.00   1.00    1.00  0.00  1.00  1.00  0.00
## NA_sales        2 583  0.56  1.22   0.16    0.27  0.21  0.00  9.73  9.73
## EU_sales        3 583  0.33  0.67   0.10    0.18  0.13  0.00  5.73  5.73
## JP_sales        4 583  0.02  0.07   0.00    0.01  0.00  0.00  0.88  0.88
## global_sales    5 583  1.02  2.09   0.35    0.54  0.43  0.01 14.77 14.76
## critic          6 583 70.49 15.12  73.00   71.71 14.83 27.00 96.00 69.00
## user            7 583  6.95  1.54   7.30    7.14  1.33  1.20  9.30  8.10
##               skew kurtosis   se
## genre*         NaN      NaN 0.00
## NA_sales      4.41    22.41 0.05
## EU_sales      4.46    24.55 0.03
## JP_sales      6.43    52.31 0.00
## global_sales  4.20    19.81 0.09
## critic       -0.68    -0.18 0.63
## user         -1.14     1.08 0.06
## ---------------------------------------------------------- 
## genre: Sports
##              vars   n  mean    sd median trimmed   mad   min   max range
## genre*          1 573  1.00  0.00   1.00    1.00  0.00  1.00  1.00  0.00
## NA_sales        2 573  0.60  1.99   0.27    0.35  0.28  0.00 41.36 41.36
## EU_sales        3 573  0.33  1.44   0.08    0.13  0.12  0.00 28.96 28.96
## JP_sales        4 573  0.05  0.30   0.00    0.00  0.00  0.00  3.77  3.77
## global_sales    5 573  1.11  4.00   0.50    0.64  0.50  0.01 82.54 82.53
## critic          6 573 72.95 13.44  76.00   74.42 10.38 19.00 97.00 78.00
## user            7 573  6.97  1.46   7.30    7.12  1.33  0.70  9.20  8.50
##               skew kurtosis   se
## genre*         NaN      NaN 0.00
## NA_sales     16.15   312.92 0.08
## EU_sales     15.26   282.22 0.06
## JP_sales      9.54   100.35 0.01
## global_sales 16.17   307.46 0.17
## critic       -1.10     1.26 0.56
## user         -0.92     0.68 0.06</code></pre>
<p>The above is a quick and dirty way of getting summary information by group. But it is messy. We suggest an alternative method which is to write code using the <code>tidyverse</code> package. This can give us descriptive statistics in a more organized way.</p>
<p>For instance, if we wanted to get the mean of the column <code>NA_sales</code> by <code>genre</code> we would use <code>group_by()</code> and <code>summarise()</code> in this way:</p>
<div class="sourceCode" id="cb727"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb727-1"><a href="descriptives.html#cb727-1" aria-hidden="true" tabindex="-1"></a>vg <span class="sc">%&gt;%</span> </span>
<span id="cb727-2"><a href="descriptives.html#cb727-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> </span>
<span id="cb727-3"><a href="descriptives.html#cb727-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanNA =</span> <span class="fu">mean</span>(NA_sales))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   genre   meanNA
##   &lt;chr&gt;    &lt;dbl&gt;
## 1 Action   0.407
## 2 Racing   0.397
## 3 Shooter  0.555
## 4 Sports   0.603</code></pre>
<p>The above code can be read as taking the dataset <code>vg</code>, and then grouping it by the column <code>genre</code>, and then summarizing the data to get the mean of the <code>NA_sales</code> column by group/genre. Please not the British spelling of <code>summarise()</code>. The <code>tidyverse</code> was originally written using British spelling, and although R is usually fine with British or US spelling, this is one situation in which it is usually helpful to stick with the British spelling for boring reasons.</p>
<p>If you had missing data, you’d do it like this.</p>
<div class="sourceCode" id="cb729"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb729-1"><a href="descriptives.html#cb729-1" aria-hidden="true" tabindex="-1"></a>vg <span class="sc">%&gt;%</span> </span>
<span id="cb729-2"><a href="descriptives.html#cb729-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> </span>
<span id="cb729-3"><a href="descriptives.html#cb729-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanNA =</span> <span class="fu">mean</span>(NA_sales, <span class="at">na.rm =</span> T)) </span></code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   genre   meanNA
##   &lt;chr&gt;    &lt;dbl&gt;
## 1 Action   0.407
## 2 Racing   0.397
## 3 Shooter  0.555
## 4 Sports   0.603</code></pre>
<p>You can do several summaries at once like this. Here we are getting the means and sample standard deviations of the <code>NA_sales</code> and <code>EU_sales</code> columns by <code>genre</code>:</p>
<div class="sourceCode" id="cb731"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb731-1"><a href="descriptives.html#cb731-1" aria-hidden="true" tabindex="-1"></a>vg <span class="sc">%&gt;%</span> </span>
<span id="cb731-2"><a href="descriptives.html#cb731-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span> </span>
<span id="cb731-3"><a href="descriptives.html#cb731-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">meanNA =</span> <span class="fu">mean</span>(NA_sales),</span>
<span id="cb731-4"><a href="descriptives.html#cb731-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_NA =</span> <span class="fu">sd</span>(NA_sales),</span>
<span id="cb731-5"><a href="descriptives.html#cb731-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">meanEU =</span> <span class="fu">mean</span>(EU_sales),</span>
<span id="cb731-6"><a href="descriptives.html#cb731-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_EU =</span> <span class="fu">sd</span>(EU_sales))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   genre   meanNA sd_NA meanEU sd_EU
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 Action   0.407 0.819  0.267 0.577
## 2 Racing   0.397 1.03   0.309 0.852
## 3 Shooter  0.555 1.22   0.331 0.667
## 4 Sports   0.603 1.99   0.326 1.44</code></pre>
<p>To save time, you can tell it to just get the summary of all numeric columns by using <code>summarise_if()</code>.</p>
<div class="sourceCode" id="cb733"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb733-1"><a href="descriptives.html#cb733-1" aria-hidden="true" tabindex="-1"></a>vg<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(vg<span class="sc">$</span>year) <span class="co"># just need to make year non-numeric first so doesn&#39;t get included in the numeric columns</span></span>
<span id="cb733-2"><a href="descriptives.html#cb733-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb733-3"><a href="descriptives.html#cb733-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb733-4"><a href="descriptives.html#cb733-4" aria-hidden="true" tabindex="-1"></a>vg <span class="sc">%&gt;%</span></span>
<span id="cb733-5"><a href="descriptives.html#cb733-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span></span>
<span id="cb733-6"><a href="descriptives.html#cb733-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, mean, <span class="at">na.rm =</span> T) <span class="sc">%&gt;%</span></span>
<span id="cb733-7"><a href="descriptives.html#cb733-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##     genre  NA_sales  EU_sales   JP_sales global_sales   critic     user
## 1  Action 0.4071013 0.2668004 0.04857573    0.8349649 68.01605 7.117954
## 2  Racing 0.3967908 0.3085100 0.03246418    0.8630946 69.84241 6.991691
## 3 Shooter 0.5554717 0.3310292 0.02288165    1.0245969 70.48714 6.948885
## 4  Sports 0.6034031 0.3260733 0.04808028    1.1108028 72.94764 6.970157</code></pre>
<div class="sourceCode" id="cb735"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb735-1"><a href="descriptives.html#cb735-1" aria-hidden="true" tabindex="-1"></a> vg <span class="sc">%&gt;%</span></span>
<span id="cb735-2"><a href="descriptives.html#cb735-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre) <span class="sc">%&gt;%</span></span>
<span id="cb735-3"><a href="descriptives.html#cb735-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, sd, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb735-4"><a href="descriptives.html#cb735-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span></code></pre></div>
<pre><code>##     genre  NA_sales  EU_sales   JP_sales global_sales   critic     user
## 1  Action 0.8189867 0.5772930 0.14425469     1.670552 14.20560 1.339989
## 2  Racing 1.0315188 0.8522769 0.24017403     2.363348 14.00640 1.497225
## 3 Shooter 1.2165479 0.6674269 0.07343275     2.087551 15.11614 1.540249
## 4  Sports 1.9868151 1.4352370 0.30421425     3.996394 13.44039 1.463734</code></pre>
<p><br><br></p>
</div>
<div id="counts-by-group" class="section level3" number="6.6.2">
<h3><span class="header-section-number">6.6.2</span> Counts by Group</h3>
<p>Another common use of <code>group_by()</code> is to get counts of how many we have of each categorical variable. For instance, let’s look more at the videogames dataset <code>vg</code>.</p>
<p>We have previously seen that we can use <code>table()</code> to count simple frequencies. For instance, the following:</p>
<div class="sourceCode" id="cb737"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb737-1"><a href="descriptives.html#cb737-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(vg<span class="sc">$</span>genre)</span></code></pre></div>
<pre><code>## 
##  Action  Racing Shooter  Sports 
##     997     349     583     573</code></pre>
<p>shows us how many observations of each genre we have. We have 997 Action games, 349 Racing games, 583 shooter games and 573 sports games.</p>
<p>We can look at how these breakdown by platform by adding one more argument into our <code>table()</code> function which relates to our second column of interest:</p>
<div class="sourceCode" id="cb739"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb739-1"><a href="descriptives.html#cb739-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(vg<span class="sc">$</span>genre, vg<span class="sc">$</span>platform)</span></code></pre></div>
<pre><code>##          
##            PC PS2 PS3 Wii X360
##   Action  144 247 237 127  242
##   Racing   48 135  63  30   73
##   Shooter 144 128 123  30  158
##   Sports   32 203 116  79  143</code></pre>
<p><br></p>
<p>We can see here that we have 32 Sports games on the PC, 135 racing games on the PS2 and so on.</p>
<p>This is a nice and straightforward way of doing this. It’s also possible to do it using the <code>tidyverse()</code> which can come in handy sometimes in some circumstances. To do it this way, we make use of <code>group_by()</code> and <code>count()</code>. We tell it the two columns we wish to group our data by (in this case it is the <code>genre</code> and the <code>platform</code> columns), and then tell it to count how many observations we have:</p>
<div class="sourceCode" id="cb741"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb741-1"><a href="descriptives.html#cb741-1" aria-hidden="true" tabindex="-1"></a>vg <span class="sc">%&gt;%</span></span>
<span id="cb741-2"><a href="descriptives.html#cb741-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(genre, platform) <span class="sc">%&gt;%</span></span>
<span id="cb741-3"><a href="descriptives.html#cb741-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<pre><code>## # A tibble: 20 x 3
## # Groups:   genre, platform [20]
##    genre   platform     n
##    &lt;chr&gt;   &lt;chr&gt;    &lt;int&gt;
##  1 Action  PC         144
##  2 Action  PS2        247
##  3 Action  PS3        237
##  4 Action  Wii        127
##  5 Action  X360       242
##  6 Racing  PC          48
##  7 Racing  PS2        135
##  8 Racing  PS3         63
##  9 Racing  Wii         30
## 10 Racing  X360        73
## 11 Shooter PC         144
## 12 Shooter PS2        128
## 13 Shooter PS3        123
## 14 Shooter Wii         30
## 15 Shooter X360       158
## 16 Sports  PC          32
## 17 Sports  PS2        203
## 18 Sports  PS3        116
## 19 Sports  Wii         79
## 20 Sports  X360       143</code></pre>
<p><br></p>
<p>These data are presented in a slightly different way. The count of each combination is shown in the new <code>n</code> column. The nice thing about this tidy approach is that we can further manipulate the data. This is better illustrated with an even busier dataset, the <code>catcolor.csv</code> dataset:</p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="descriptives.html#cb743-1" aria-hidden="true" tabindex="-1"></a>cats <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/catcolor.csv&quot;</span>)</span>
<span id="cb743-2"><a href="descriptives.html#cb743-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cats)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   animal_id monthyear           name        color1 color2 sex    breed        
##   &lt;chr&gt;     &lt;dttm&gt;              &lt;chr&gt;       &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;        
## 1 A685067   2014-08-14 18:45:00 Lucy        blue   white  Female domestic sho~
## 2 A678580   2014-06-29 17:45:00 Frida       white  black  Female domestic sho~
## 3 A675405   2014-03-28 14:55:00 Stella Luna black  white  Female domestic med~
## 4 A684460   2014-08-13 15:04:00 Elsa        brown  &lt;NA&gt;   Female domestic sho~
## 5 A686497   2014-08-31 15:45:00 Chester     black  &lt;NA&gt;   Male   domestic sho~
## 6 A687965   2014-10-31 18:29:00 Oliver      orange &lt;NA&gt;   Male   domestic sho~</code></pre>
<p>Say we want to know how many male and female cats of each breed we have. With tidyverse, we would do it like this:</p>
<div class="sourceCode" id="cb745"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb745-1"><a href="descriptives.html#cb745-1" aria-hidden="true" tabindex="-1"></a>cats <span class="sc">%&gt;%</span></span>
<span id="cb745-2"><a href="descriptives.html#cb745-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(breed,sex) <span class="sc">%&gt;%</span></span>
<span id="cb745-3"><a href="descriptives.html#cb745-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span></code></pre></div>
<pre><code>## # A tibble: 87 x 3
## # Groups:   breed, sex [87]
##    breed                   sex        n
##    &lt;chr&gt;                   &lt;chr&gt;  &lt;int&gt;
##  1 abyssinian              Female     2
##  2 abyssinian              Male       1
##  3 american curl shorthair Female     4
##  4 american curl shorthair Male       1
##  5 american shorthair      Female    28
##  6 american shorthair      Male      44
##  7 angora                  Female     4
##  8 angora                  Male       2
##  9 angora/persian          Male       1
## 10 balinese                Female     3
## # ... with 77 more rows</code></pre>
<p><br></p>
<p>This gives us a lot of information. In fact, we have 87 rows of data. However, we could next sort by the newly created <code>n</code> column, to see which sex/breed combination we have the highest amount of. We can use <code>arrange()</code> to do this:</p>
<div class="sourceCode" id="cb747"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb747-1"><a href="descriptives.html#cb747-1" aria-hidden="true" tabindex="-1"></a>cats <span class="sc">%&gt;%</span></span>
<span id="cb747-2"><a href="descriptives.html#cb747-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(breed,sex) <span class="sc">%&gt;%</span></span>
<span id="cb747-3"><a href="descriptives.html#cb747-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">%&gt;%</span></span>
<span id="cb747-4"><a href="descriptives.html#cb747-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>n)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 3
## # Groups:   breed, sex [87]
##    breed               sex        n
##    &lt;chr&gt;               &lt;chr&gt;  &lt;int&gt;
##  1 domestic shorthair  Male    6303
##  2 domestic shorthair  Female  4757
##  3 domestic mediumhair Male     702
##  4 domestic mediumhair Female   512
##  5 domestic longhair   Male     381
##  6 domestic longhair   Female   328
##  7 siamese             Male     214
##  8 siamese             Female   135
##  9 maine coon          Male      54
## 10 snowshoe            Male      45
## # ... with 77 more rows</code></pre>
<p><br></p>
<p>Another thing we can do is to count how many there are of a given category or categories that satisfy certain conditions. For example, let’s say we wanted to know the most popular name of each breed for orange cats. We could first filter the data by <code>color1</code> to only keep orange cats, then group by <code>name</code> and <code>breed</code> and then use <code>count()</code> and <code>arrange()</code>:</p>
<div class="sourceCode" id="cb749"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb749-1"><a href="descriptives.html#cb749-1" aria-hidden="true" tabindex="-1"></a>cats <span class="sc">%&gt;%</span></span>
<span id="cb749-2"><a href="descriptives.html#cb749-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(color1 <span class="sc">==</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb749-3"><a href="descriptives.html#cb749-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name,breed) <span class="sc">%&gt;%</span></span>
<span id="cb749-4"><a href="descriptives.html#cb749-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb749-5"><a href="descriptives.html#cb749-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>n)</span></code></pre></div>
<pre><code>## # A tibble: 1,304 x 3
## # Groups:   name, breed [1,304]
##    name     breed                  n
##    &lt;chr&gt;    &lt;chr&gt;              &lt;int&gt;
##  1 Oliver   domestic shorthair    16
##  2 Oscar    domestic shorthair    12
##  3 Ginger   domestic shorthair    11
##  4 Sam      domestic shorthair    11
##  5 Garfield domestic shorthair    10
##  6 Simba    domestic shorthair    10
##  7 Tiger    domestic shorthair    10
##  8 Toby     domestic shorthair    10
##  9 Charlie  domestic shorthair     9
## 10 Milo     domestic shorthair     9
## # ... with 1,294 more rows</code></pre>
<p>It turns out that the most popular names overall for orange cats are for domestic shorthairs who are called Oliver, then Oscar, Ginger, Sam, Garfield and so on.</p>
<p>To do exactly what we said above, we can do something a bit different. After we’ve done all the above, we can then tell the chain that we only want to group by <code>breed</code> this time, and we want to keep the highest value with <code>top_n(1)</code>. This returns the following:</p>
<div class="sourceCode" id="cb751"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb751-1"><a href="descriptives.html#cb751-1" aria-hidden="true" tabindex="-1"></a>cats <span class="sc">%&gt;%</span></span>
<span id="cb751-2"><a href="descriptives.html#cb751-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(color1 <span class="sc">==</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb751-3"><a href="descriptives.html#cb751-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(name,breed) <span class="sc">%&gt;%</span></span>
<span id="cb751-4"><a href="descriptives.html#cb751-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb751-5"><a href="descriptives.html#cb751-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="sc">-</span>n) <span class="sc">%&gt;%</span> </span>
<span id="cb751-6"><a href="descriptives.html#cb751-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(breed) <span class="sc">%&gt;%</span></span>
<span id="cb751-7"><a href="descriptives.html#cb751-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">top_n</span>(<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 23 x 3
## # Groups:   breed [11]
##    name    breed                   n
##    &lt;chr&gt;   &lt;chr&gt;               &lt;int&gt;
##  1 Oliver  domestic shorthair     16
##  2 Boris   domestic mediumhair     5
##  3 Pumpkin domestic mediumhair     5
##  4 Charlie domestic longhair       3
##  5 Gilbert domestic longhair       3
##  6 Pumpkin domestic longhair       3
##  7 Amos    american shorthair      2
##  8 Roxy    cymric                  2
##  9 Alise   manx                    1
## 10 Ami     british shorthair       1
## # ... with 13 more rows</code></pre>
<p>Charlie, Gilbert and Pumpkin are all the most common names for orange domestic longhairs!</p>
<p><br>
<br></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-visualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="distributions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jalapic/introstats/edit/master/05-Descriptives.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/jalapic/introstats/blob/master/05-Descriptives.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
